### ISSUE TITLE
Add PINEMAP watermark to maps?

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#20]
Try adding a watermark to see how it looks in one corner of the maps.  It would give "mandatory attribution" in screenshots from the DSS.

**Comment by daviswx** [comment]
It turns out that this is a bit tougher than I thought.  With OpenLayers v2, it was easy to embed an image tag in your map, like on the CRONOS Map.  However, it's not as straightforward in OpenLayers v3; doing that causes the map itself to shift around strangely.

I think there are probably options for doing this, but I'll need to do some more searching and testing.

Also, my initial plan was to have the watermark/corner logo appear on only one map (whichever one is enlarged), similar to the zoom controls and map scale feature.  Let me know if you think it would be better to put it on all three maps.

**Comment by hadinon** [comment]
Ahhh ok gotcha. Just thought of this -- what if you "left justify" (instead of center) the color legend and text above the map and in addition, include the PINEMAP logo to the right of that text and the color legend?

I'm thinking if folks take a screenshot they will want to include the color legend and thus, the PINEMAP logo should always be included.

**Comment by daviswx** [comment]
Here are mockups for a few different design possibilities I thought of:

**Option A:** Fully left-justifying the legend with the PINEMAP logo on the right (same as your idea)
![legend-logo-a](https://cloud.githubusercontent.com/assets/9257580/9394246/6e2a94f4-4755-11e5-9b6c-c7e10f356438.png)

**Option B:** Keeping the legend and logo next to each other, but centered over the map
![legend-logo-b](https://cloud.githubusercontent.com/assets/9257580/9394278/8e142fbe-4755-11e5-8e3c-481bac29c4f2.png)

**Option C:** Putting a small PINEMAP logo in the title bar of the enlarged map
![legend-logo-c](https://cloud.githubusercontent.com/assets/9257580/9394282/9976c9c0-4755-11e5-8ea2-7cddca155d41.png)

**Option D:** Putting a small PINEMAP logo as a fixed watermark on the map
![legend-logo-d](https://cloud.githubusercontent.com/assets/9257580/9394292/a5ae94fc-4755-11e5-945f-0e8d31595d51.png)

Any preference among these, or any other ideas?

**Comment by hadinon** [comment]
I don't have an absolute favorite but I like options C and D better than A and B. Do you have a favorite? Maybe we should get Ryan's thoughts? It looks like he's at a climate adaptation meeting during our weekly meeting tomorrow so maybe we can email these options instead of sharing during our meeting?

**Comment by daviswx** [comment]
My own preference is with D since (1) it's fairly discreet, and (2) even if someone only screencaps the map itself, they will still capture the logo.  It also matches what we talked about at last week's meeting.

I'll keep working on figuring out a way to add it as an overlay on the map.

**Comment by hadinon** [comment]
Yeah, I agree. Let's go with option D. Thanks!

**Comment by daviswx** [comment]
The PINEMAP logo/link is now in place at the bottom right corner of the enlarged map.
