### ISSUE TITLE
Map "save as" option with right click

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#25]
Disable this feature, if possible, because it doesn’t capture title or PINEMAP logo (LOW PRIORITY).

**Comment by daviswx** [comment]
I don't think this is possible because it's an option with the browser, not with OpenLayers itself.  As best as I can tell, the OpenLayers v3 renderer creates a canvas containing all of the map layers, and the browser treats this as an image.  The other options (scale bar, zoom icons, attribution incl. PINEMAP logo) are added on top of this.  And the map title is a completely separate HTML element.

I'm flagging this as "wontfix" and closing the issue for now, but if the PINEMAP higher-ups deem this to be an important issue, maybe we can find some way around it.

**Comment by hadinon** [comment]
Sounds like a good plan to me. Thanks
