### ISSUE TITLE
Extreme Min Temp Tool: Color Ramp Suggestions

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#27]
*Reverse the color ramp for occurrence maps (warm sites/low values = red, cold sites/high values = blue)
*Maybe remove green color in the Projected Change color ramp since green could be associated with good?
(MEDIUM PRIORITY)

**Comment by daviswx** [comment]
I added new color ramps for this tool.  I think the Projected Change one is fine; it's basically the same as before but without the green.

For the Historical and Projected Occurrence displays, I basically reversed the color ramp, and I don't like how it looks.  For one, in my mind, pink and red correspond to high values, but they are associated with low values here.  Also, the color range from yellow → orange → red → pink is also used for the Projected Change map, but the order is reversed (from low to high instead of high to low).

I think I will probably re-do the Occurrence palette with non-conflicting colors.  I'm thinking of maybe the [USDA plant hardiness zone color ramp](http://planthardiness.ars.usda.gov/PHZMWeb/images_ui/homepage_map.jpg), from brown/beige → green (sorry, Eric) → blue → purple.  That way, we also avoid having any red colors and it being misinterpreted as red = warm or red = high values.

**Comment by daviswx** [comment]
I made the new changes to the Historical/Projected Occurrence palette.  In case you didn't get to see the last version, here's the comparison.

**Version A**
![extrememintemp-palettea](https://cloud.githubusercontent.com/assets/9257580/9800307/55178b26-57da-11e5-9f00-a03305767794.PNG)

**Version B**
![extrememintemp-paletteb](https://cloud.githubusercontent.com/assets/9257580/9800311/5a567426-57da-11e5-813f-db7498c9ccc7.PNG)

I definitely prefer the second version, although I may remove some of the bluish-purple colors since I have a hard time telling them apart.

**Comment by daviswx** [comment]
As of last Friday, the slightly updated color ramp is in place:
![extrememintemp-palettec](https://cloud.githubusercontent.com/assets/9257580/9883692/97d5dad0-5ba9-11e5-9066-4e050cc04159.PNG)

I personally like how this one looks, so unless you or the beta testers have any suggestions, this will probably be what we go with for this tool.
