### ISSUE TITLE
Seedling Deployment Tools Bug

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#3]
Corey,

This issue occurs across both seedling deployment tools on this DSS version:
http://nc-climate.ncsu.edu/pinemap_dss/index.php

Here are the steps to replicate this:
1) Turn off all current and projected isotherms except one, e.g. baseline isotherm.
2) Click "show details" to display the options for the seed selection range. When you click, all current and projected isotherms are drawn on the map (instead, I would expect just the baseline isotherm to remain on the map). 
3) If you select a range option from the drop down menu, the map changes appropriately but then when you hit "hide details", it displays all current and projected isotherms instead of the "checked option" (in this case, the baseline isotherm).

Related.... 
1) Turn off all current and projected isotherms except one, e.g. baseline isotherm.
2) Users still have the ability to click "show details" on a _different_ isotherm even though that box is not checked. Should we disable the "show details" click for isotherm layers that are not checked? 
Note: I doubt many people would do this but you never know! If they do and then they decide to choose a seed selection range, it might get confusing because the output displayed does not correspond with the isotherm box that is checked.

I hope that makes sense! Let me know if you need any clarification on this.

Thanks,
Heather

**Comment by daviswx** [comment]
Quick summary of this to jog my memory later:
When un-selecting a _seed selection range_ (either by clicking 'hide details' or selecting no range), the JavaScript function should check which isotherms are checked, rather than turning them all back on.

This probably won't be an immediate fix since I'm just starting to dig into my JavaScript code as a part of the tool layout overhaul.  But I'll definitely make sure it gets fixed!

Also, good idea about disabling the "show details" links for non-selected isotherms.  I'm not sure exactly how these checkboxes or options will look on the new design, but it is something I will implement.

**Comment by daviswx** [comment]
This bug should be fixed as of the current alpha version.  When hiding a recruitment/risk range, only the checked isotherms should be displayed.
