### ISSUE TITLE
Three-map Layout

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#31]
*Change occurrence map titles to “Minimum Projected Occurrence”, “Mean Projected Occurrence”, “Maximum Projected Occurrence” and add tooltips to explain these (e.g. minimum projected occurrence = historical average + minimum projected change)
*On the enlarged map title, disable the hover-over mouse pointer
*Disable clicking on the small maps to select a location, clicking on them should enlarge them
*Add a loading icon over the map(s) while layers are loading
(HIGH PRIORITY)

**Comment by daviswx** [comment]
A few updates and questions about this:
- When hovering over the enlarged map title, the background no longer turns blue and the cursor doesn't change to a pointer.
- The small maps are no longer clickable to select a location.  However, I'm not sure whether we want to make it so that clicking them automatically enlarges them.  I imagine that could cause some frustration if users errantly click on these maps.
- The Projected Occurrence map titles have been changed as suggested.  I haven't added in the tooltip because I thought it might be confusing to have two tooltips next to each other (the projected occurrence tooltip and the 'click the map title to enlarge' tooltip).  But I do think it's important to have this information displayed somewhere.
- I noticed that on the seedling deployment tools, the Projected Temperature map titles are labelled "Min/Mean/Max Projected Change".  Is this the appropriate way to label them?  Or would something like "Min/Mean/Max Projected Temperatures" be better?
- I wanted to get some clarification about the final item (adding a loading icon over the map) since I can't remember what we had discussed.  Did we want to do this _only_ when selecting a location?  Or any time map layers were loading (like when you change the Map Display or pan/zoom)?  It seems that this feature isn't natively built in to OpenLayers v3, so either way it will require some trickery like I did with the layer switcher and watermark.

**Comment by daviswx** [comment]
More updates:
- At today's meeting, we discussed disabling the pan and zoom functions on the small maps so they are basically static.  I don't think OpenLayers will let you completely turn off these functions, so we may have to at least allow panning and zooming (which isn't a big deal IMO).  I think it's still a good idea to ask the beta testers what behavior they would expect/prefer when clicking on the side maps.  I can think of several different answer choices: nothing; pan by clicking and dragging + zoom by double-clicking; drop a marker at the clicked location; or, enlarge the clicked map.
- The map titles on the seedling deployment tools are now labelled "Min/Mean/Max Projected Temperatures".
- When the Projected Occurrence display is selected, tooltips will display in the map titles.

For now, I will leave this issue open but flag it as a question since we will wait to hear from the beta testers about the small map interaction.

**Comment by hadinon** [comment]
Below is some feedback regarding the last item in this issue... the need for a loading icon. One of our testers, Steven Weaver, says:

**In Chrome browser, tested all tools, and lag noted:**
- on initial load. It appears to be occurring when the browser requests the data layer the first time.
- on initial load of county outlines. Can toggle on and off with no lag after initial load.
- on map extent change. when zooming out, it takes a while to load the missing map tiles. Maybe make the current max extent the default extent, or maybe make the current default extent the max extent.
- when switching between tools for the first time (temp and precip tools), I think this is primarily due to loading a data layer for the tool being switched to.
- when changing time slices or climate scenarios for the first time (temp and precip tools), layers can be switched after initial load without any delay
- when switching tools or scenarios on seedling deployment tools, lag on intial layer loads. range layers or scenarios can be toggled without lag after initial load.

**For loading issues, in summary:**
- most lag noted when browser requesting data layers for the first time (map or tool loading, time slice or scenario changes, map extent changes, turning on county lines)

**Note:**
- map layers would not load for me in IE 11. Map frame loaded fine. I cleared cache and reloaded without success. Layer request seems to be timing out maybe. Problem may be on my end, but I thought I would note it.
- Seedling tools projected temperatures data took extra long to load (2+ min) in Chrome. Maybe a network issue today. I don't think it took that long when I used it before.
- In Chrome, on all of the 'Environment' tools, the label 'Projected change' on the Map display radio button disappears for me when 'Projected occurrence' is selected.

**Comment by hadinon** [comment]
A few comments...
- the IE11 issue is fixed (see #44)
- there was a rogue tomcat process yesterday that was slowing down THREDDS -- I believe this is why the seedling tools projected temperatures took so long to load. Nathan fixed this issue so I will have Steven try it again today.
- the disappearing projected change radio button is fixed (see #34)

**Comment by daviswx** [comment]
Regarding the loading icon, I have some good news and some bad news.
- **Good News:** I have been able to implement a loading screen over the maps when the map is clicked.  It doesn't disappear until data is retrieved from the selected location, and it's impossible to click a different location while it's loading (i.e., it's Ryan-proof :smile:).  When a location is selected, the loading screen also shows up when switching from one Map Display to another since it has to load the new data for the selected location.
- **Bad News:** OpenLayers 3 apparently doesn't have the built-in ability to track when layers start and end loading, so I don't know that it's possible to show this loading screen and have it disappear when the map first loads or when panning/zooming.

I should qualify that with one caveat: Apparently they have added some experimental [tile load events](http://openlayers.org/en/master/examples/tile-load-events.html) in the latest version, 3.7.0.  The DSS is running v3.0.0, though, and upgrading isn't as simple as changing the version number.  As versions have changed, so has the syntax for a few important features, so upgrading would require re-writing chunks of the map code.

I'm not really sure how long that would take, but since we're so close to the next round of beta testing, I'd be a bit afraid to start upgrading now if it took a while or unexpected bugs came up.

So here's what I'm thinking:
- We keep the DSS on the "ol' reliable" version of OpenLayers through the next round of beta testing, and I can start investigating the new version during that time.
- For now, we show the loading screen when selecting a location (and changing the map display when a location is selected).  Should the on-screen text say "Loading Map Data" or "Loading Location Data" or something else?
- During beta testing, maybe we can ask about the delay in layers loading to gauge when we should show the loading screen.  For instance, the layers seem to take the longest to load when you first come to a tool or view a new map display.  For me, loading is quicker when panning/zooming, so I'm not sure whether we need to show the loading screen each time the user pans or zooms.  Perhaps we could ask the beta testers how long it takes for the map layers to load in each instance: when the map first loads, when switching to a different Map Display, and when panning/zooming.

Sound like a good plan to you?

**Comment by daviswx** [comment]
One other change: As we discussed earlier, I have changed the Historical Occurrence and Projected Occurrence options to **Historical Average** and **Projected Average**.  This change should be reflected in the menu options, the map titles, and the timeseries.

**Comment by hadinon** [comment]
I know we just discussed this but I'll write it here just in case we ever need to look back at this! 

I'm good with all the above changes and agree with your proposed plan for moving forward. I've updated the beta tester question document to reflect the items/questions mentioned above.

Lastly, I agree with what you mentioned during our discussion -- because the loading icon is tied to location information right now, let's stick with the "Loading Location Data" on-screen text.

**Comment by hadinon** [comment]
Steven Weaver noticed a significant lag in loading the seedling deployment tools the other day (mentioned above). He just confirmed that this significant lag is no longer present.

**Comment by daviswx** [comment]
After updating the maps to OpenLayers v3.4.0, I was able to add a progress bar when the map layers are loading.  It seems to be working for all tools on the development site.

I think that's the only outstanding topic with this issue, so I am closing it.  Please re-open (or start a new issue) if problems are found with the loading bar.

**Comment by hadinon** [comment]
We still need to resolve the small map interaction, right? If that is already listed in another issue please feel free to re-close this. During the small group beta tester calls, I believe we plan to ask their opinion on enlarging the small map AND dropping a marker upon clicking the map. I'm guessing they will be OK with it. Once that's implemented, this should be good to close.

**Comment by hadinon** [comment]
Action items from beta testing: 
*Change wording to “Highest/Lowest Likely” (per IPCC likelihood guidance -- https://www.ipcc.ch/pdf/supporting-material/uncertainty-guidance-note.pdf) and “Multi-model Mean”.  Add subtitles saying “2.5th Percentile” and “97.5th Percentile”. 
*Keep tooltips in map titles for change and projected average displays stating that these represent two std deviations above/below mean and two std deviations above/below mean + historical avg, respectively. 
*Also clarify (with images) the percentiles and standard deviations in the FAQ box -- be sure to mention that this is an absolute change. 
*Adjust the wording on the time series legend to say “range of likely possibilities/outcomes”. Also change the tooltip wording for the time series legend to note 2 standard deviations/percentiles.
(HIGH PRIORITY)

**Comment by hadinon** [comment]
Additional action items from beta testing: 
*Move the enlarge icon closer to the title text and add "ENLARGE" text beneath it.
*Allow dropping a marker on the side maps.
*Add this to the FAQ for side maps: “you can zoom in on the side maps without changing the location that’s already selected”
(MEDIUM PRIORITY)

**Comment by hadinon** [comment]
Action item from beta survey:
*Make minor roads black
(LOW PRIORITY)

**Comment by daviswx** [comment]
Here are two examples of "enlarge" button placement (with the updated icon):

**Far right of title bar**
![maps_enlarge_a](https://cloud.githubusercontent.com/assets/9257580/11480241/61370692-9764-11e5-9487-49a98275ecc0.PNG)

**Centered with the title**
![maps_enlarge_b](https://cloud.githubusercontent.com/assets/9257580/11480267/93a5a69c-9764-11e5-8648-058780b718c7.PNG)

Any thoughts about these after seeing them on the page?  When it's centered with the title (and tooltip), is it too cluttered?  Or, like the beta testers suggested, do you think it's easier to see the icon this way?

Also, any thoughts on having the "ENLARGE" text below the icon?

**Comment by hadinon** [comment]
I really like it centered. How about you? The placement of "ENLARGE" below the icon looks great.

**Comment by daviswx** [comment]
I also like the "ENLARGE" text on it.  As far as the placement goes, I don't have much of a preference one way or the other since there's only a small difference.  But since you prefer the centered version, I went ahead and implemented that.

One very minor thing I've noticed is that when you hover over the side map titles, the underline extends one space to the right of the name and butts up against the Enlarge button.  I wasn't able to find a quick solution to this after quickly playing around with the CSS, but I'm sure it can be fixed.  If I have time, I will try to get back to it before the end of the week.

**Comment by daviswx** [comment]
Other updates for this issue:
- Clicking on the side maps to select a location has been re-enabled.
- Since this is in place, is it still appropriate to add the note about zooming in on the side maps without changing the selected location?  My main reservation is that people may double click to zoom, and if they double click the side maps, it _will_ change the selected location.
- Regarding the road colors, we're currently getting the major road, minor road, and city layers from the OpenGeo server, so I can't set a custom styling for those.  We do have two of those three layers on our own GeoServer, so we can specify a custom style for each, but it will require a bit more work to make it look and function like the current version (e.g., having the minor roads only display once you zoom in to a certain level, and controlling the density of the city labels).  I will keep this on my to-do list, but it probably won't be done before the rollout.

Is that everything we needed to do regarding the maps?

**Comment by hadinon** [comment]
I see what you mean about the underline extending slightly and agree it is lower priority. 

Yeah, good point about that side map note. I agree that is not necessary anymore.

Sounds good about the roads. Maybe we keep this open until that and the other minor underline issue is resolved?

Other than that, there were a few other action items listed above (from beta testing):
- Change wording on 3 map titles to “Highest/Lowest Likely” (per IPCC likelihood guidance -- https://www.ipcc.ch/pdf/supporting-material/uncertainty-guidance-note.pdf) and “Multi-model Mean”. 
- Add subtitles to side maps saying “2.5th Percentile” and “97.5th Percentile”. 
- Also clarify (with images) the percentiles and standard deviations in the FAQ box -- be sure to mention that this is an absolute change -- do we still want to do this?
- Adjust the wording on the time series legend to say “range of likely possibilities/outcomes”. Also change the tooltip wording for the time series legend to note 2 standard deviations/percentiles.
  -- For this one, I think we addressed the second half within the FAQ box. Maybe adding the word "likely" in front of "possibilities" on the time series legend would suffice since we don't want to use that awful "r" word. :smile:

**Comment by daviswx** [comment]
A few updates about this so far:
- I have created a new issue (#72) about the Roads & Cities layers to better summarize that issue so it's easier for me to tackle once I have time.
- For the map wording, did we want to say "Highest Likely", or "Highest Likely Change" and "Highest Likely Average/Outcome"?  To me, just having "Highest Likely" and "Lowest Likely" looks a bit incomplete.
- Could you come up with some wording about the percentiles and standard deviations?  I assume this will go in the "What do the side maps show?" FAQ box.  We can include an image if needed, but I'm not sure whether we need one.
- I updated the time series legend wording to say "Likely outcomes".  We could also add a note in the tooltip about the standard deviations/percentiles, but I tried adding something to that effect and it made the tooltip pretty lengthy.

**Comment by hadinon** [comment]
Yeah, I agree with "Highest/Lowest Likely Change" and "Highest/Lowest Likely Average" -- still don't 100% love that wording but it may be our best option at this point (I can't think of anything better). 

As far as clarifying the percentiles and std deviations in the side map FAQ box, could it be as simple as re-wording the first sentence as, "...the multi-model mean, or the 2.5th percentile and 97.5th percentile"? I think defining this as an absolute change is covered in the Time Period tooltip. I'm thinking an image is not necessary. Thoughts?

Yep, I agree with your time series legend changes and not changing the time series tooltip.

**Comment by hadinon** [comment]
Do we also want to apply the "Highest/Lowest Likely" terminology and subtitles to the seedling deployment tools? Side maps might say, "Highest/Lowest Likely Temperatures" instead of "Minimum/Maximum Projected Temperatures". Center map title could say, "Multi-Model Mean Temperatures". Thoughts?

**Comment by daviswx** [comment]
Updated FAQ wording, map titles, and map subtitles are now in place.

**Comment by daviswx** [comment]
The _updated_ updated map title wording ("Highest/Lowest Likely Change/Outcome/Temperatures") is now in place, and the subtitles are turned off.

**Comment by hadinon** [comment]
At our meeting yesterday, we talked about making the "Show Layers" box expand by default since some of the eye tracking participants couldn't seem to find it.

**Comment by daviswx** [comment]
I've tried something a bit different with the map controls to address this.

First, I expanded the Show Layer Options box, but it overlapped with most of VA and parts of NC within the native loblolly range.  So I moved this box to the top left corner of the map and moved the zoom controls to the right side.

Take a look at it and let me know what you think.

**Comment by hadinon** [comment]
Yes, I love this! I'm going to close the issue (again, ha) but re-open if needed. :smile:

**Comment by hadinon** [comment]
One minor note: the first two paragraphs of the map FAQ box will need to be tweaked (switch "upper left corner" and "upper right corner"). I'm not going to re-open since it seems like an easy fix. :wink:

**Comment by hadinon** [comment]
Also, maybe we should just call it "Layer Options"? I don't vote for disabling the ability to click and hide it but just think it might be better to call it "Layer Options". Agree? Disagree?

**Comment by daviswx** [comment]
FAQ box wording is updated.

I'm fine with calling it "Layer Options".  Maybe instead of saying "Show" or "Hide", we should just have a small :heavy_plus_sign: or :heavy_minus_sign: icon in the top right corner?

**Comment by hadinon** [comment]
Yes, I like the +/- idea. :+1:

**Comment by daviswx** [comment]
This is now in place.

**Comment by hadinon** [comment]
Minor tweak then we can close this: the map FAQ box needs to be changed to say, **"Layer Options"** instead of **"Show Layer Options"**.

**Comment by daviswx** [comment]
Done. :+1:

**Comment by hadinon** [comment]
Alter text from "Loading Location Data" to add something like "Scroll to see chart below".

**Comment by daviswx** [comment]
I have updated the text to read "Loading location data on the map and in the time series below".  Since the data loads fairly quickly, this message isn't on the screen long, so I wonder whether users will actually read it.  Frankly, that is probably true with _any_ text we'd put there.

My other idea with this was to add an overlay at the bottom of the screen when the time series loads.  Once a user scrolls down, the overlay would disappear, but until then, it might be a useful cue that more information is available at the bottom of the page.  Here's a mockup of how that might look:

![timeseries_loadingoverlay](https://cloud.githubusercontent.com/assets/9257580/14817651/8767b1f4-0b86-11e6-8a0a-ffda7a3889c8.png)

**Comment by daviswx** [comment]
I restored the map loading text to its original version ("Loading Location Data") and added an overlay at the bottom of the screen that appears when the map is clicked and disappears when the entire time series chart is visible.

**Comment by daviswx** [comment]
It sounds like we're all happy with this overlay at the bottom of the screen, and I don't think there were any other outstanding action items with this issue, so I am closing it.

**Comment by daviswx** [comment]
After viewing the DSS on large screens at the annual meeting, the time series loading notification at the bottom of the screen was less obvious than we hoped for.  I will try changing the background color from the PINEMAP greenish-aqua color to a brighter green, like the one used when the location box flashes.

**Comment by daviswx** [comment]
I have changed the time series loading notification background to be a brighter green color.  I also made it a bit taller and made the font slightly larger.

![image](https://cloud.githubusercontent.com/assets/9257580/15712605/0180412e-27e1-11e6-81c3-c4c732e4a83a.png)

I think it should be more noticeable this way, but if we feel like it still isn't, I can make it pulse as well.

**Comment by hadinon** [comment]
Looks good to me. Closing this issue but feel free to re-open if necessary.
