### ISSUE TITLE
Climate change scenario wording

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#35]
*change it to Future Emissions: Current Levels (High) and Reduced Levels (Moderate)
*by default, select RCP8.5
(HIGH PRIORITY)

**Comment by daviswx** [comment]
I have updated the wording for the RCPs in the menu (and set RCP 8.5 as the default), in the map legend, in the timeseries tooltips, and in the timeseries legend.

I haven't yet updated the tooltip or added it in the map legend because I'm planning to slightly re-do the way the tooltips are created.  See the note about that in the "Tooltip Suggestions" issue (ncsco/pinemap-dss-help#33).

**Comment by hadinon** [comment]
On the Summer Precip tool (and possibly other tools), the timeseries tooltip values are not matching up with the values on the maps above. It seems like the RCP description for either the map or timeseries is switched. I think it may be the timeseries description but maybe you can double check?

![image](https://cloud.githubusercontent.com/assets/886682/9850610/c9e92286-5ac1-11e5-865a-c7eee80e0912.png)

![image](https://cloud.githubusercontent.com/assets/886682/9850580/95cbf348-5ac1-11e5-91ec-3e1253bc0517.png)

**Comment by daviswx** [comment]
Good catch.  I had a couple lines reversed in the timeseries code for all 3 climate tools.  This should be fixed now.
