### ISSUE TITLE
Extreme Min Temp Tool: RCP label missing

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#4]
On the dev site, when you select projected change or projected occurrence, the description above the map does not include whether this is moderate or intense warming.

**Comment by hadinon** [comment]
Related....  the part saying, "compared to the 1986-2005 baseline period" is actually incorrect (it is relative to 1950-2005 baseline period).

**Comment by daviswx** [comment]
Just a heads up, but this is on my short list of changes to implement soon.  I'm thinking of re-organizing the legend titles to be less wordy, better organized, and standardized across all tools.  Here's an example of what I'm thinking.  Note: font sizes are enlarged here compared to how they'll appear on the DSS.  And ignore the space between lines.

#### Projected number of days per year with minimum temperatures < 32°F

**Time Period:** 2020-2039 &nbsp;&nbsp;&nbsp; **Climate Change Scenario:** Moderate warming

We can, of course, include tooltips next to each item like we have now for explaining the baseline period.  And the wording can be adjusted as needed, like for "Climate Change Scenario", since I imagine we'll change that.

Does this look good to you?  Can you think of any other info that should be included in the legend?  Or other display ideas?

One question I had is how we should display units, like for the summer precip tool, where the data is in inches.  Should the units be in the title (e.g., "Historical average summer precipitation, in inches") or next to the legend color scale?  For some tools like Extreme Min Temp Risk, I imagine it could go in multiple places, since the legend is in days, but 'days per year' is also a key part of the description.

And getting real fancy, should we include an option (like with a dropdown) to _change_ the units?  So if you change the precip from inches to cm, it would convert everything in the scale and the timeseries.  Maybe that would be a good question for the next round of beta testing.

**Comment by hadinon** [comment]
I like that legend layout! For the projected change legend, would you just say, "Projected change in number of days..."? 

Other than what you have, it'd be nice to have a tooltip next to the time period and that could be where we explain that these future differences are relative to the model baseline period of 1950-2005 since that will be consistent for all tools and all future time periods. Thoughts?

For the units, what would it look like if it were next to the legend color scale? I'm okay with having it in multiple locations for some or all tools.

Also, yes, let's ask the beta testers about whether they'd like to change the units. I started a document for beta tester questions about the climate risk tools (mainly so I wouldn't forget) so I'll add it to that document and share it when we're ready to start refining those questions. Sound good?

**Comment by daviswx** [comment]
The Extreme Min Temp Risk and Summer Precip tools now have updated legends.  This includes a larger title font size, added subtitles for the time slice and RCP, and units next to the legend scales.

I re-added a tooltip for the historical time slice, but I haven't added tooltips for the future time periods or climate change scenarios (we really need to change that name, too!).

By the way, hopefully you can provide some clarification for me about the historical period.  I was thinking we wanted to use 20-year time slices across the board, but maybe that was just for the future periods?  I just want to make sure we're correct in saying the historical time period is from 1950 to 2005 (not 1986 to 2005, as I had previously).

Also, should we reference this as the "historical" period instead of the "baseline", since (I assume) it's using the historical Idaho data instead of the MACA baseline?  Or am I completely off base about this?

**Comment by hadinon** [comment]
Thanks! The new legends look good. Yes, let's add the "climate change scenario" wording issue to the Aim 6 document. Maybe they can help us flesh that wording out.

As far as the historical period... there are two different things going on here. Let me explain! So, the historical avg period is still 1986-2005. This is generated using the Idaho MetData. There is also model baseline data for each downscaled GCM and this data covers the historical period from 1950-2005. This model baseline data is what is used to compute the future difference maps. MACA recommends using the full model baseline period for this reason (explained under one of their FAQs here -- http://maca.northwestknowledge.net/MACAfaq.php):

"Also, note that the choice of the baseline period (here 1990-2000) may have other consequences on your comparison. The baseline period is a reference period for calculating the respective future climate change. Choosing Different reference periods for the baseline will result in different projections for change. Further, baseline periods that are chosen as subsets of the period 1950-2005 (i.e. 1990-2000 or 1971-2000) will result in variations in the baseline between the models since the MACA process maps the statistics of the period 1950-2005 to the statistics of the training data. If you wish to avoid inter-model variations in the baseline, choose 1950-2005 as a baseline. As seen in the 'Analysis - Bias Maps' tab on this webpage, this will result in minimal biases between the models and the training data."

As an example, for the model CanESM2, I first compute the avg across all model baseline years (1950-2005). Then, I compute the avg for a future period (say, 2020-2039) for RCP 4.5. I subtract the baseline avg from the future avg to get my difference value. This process is repeated for each of the 20 models so that we get 20 differences for the RCP 4.5 2020-2039 future period relative to the 1950-2005 model baseline. Then, I compute the mean of these 20 differences. Finally, I compute the standard deviations (+/-1 and +/-2) of these 20 differences and add those values back to the mean differences. This process is repeated for all 4 (or 6 for the seedling deployment tools) future time periods and for both RCPs. I guess the final final step is to compute the historical avg file, regrid it, and add it back to the difference files (mean, mean+/-1stddev, mean+/-2stddev). 

Wow, that was a lot. Does all of that make sense? For another example, feel free to check out the Dec 5th ATP presentation. There are about 20-25 different steps/scripts for each of the variables (e.g. summer precip) so it is a pretty complex process to generate the 41 final maps!

**Comment by daviswx** [comment]
Ohhhhhh... I just figured out where my confusion was coming in.  In your earlier comment, I guess you were talking specifically about the legend or tooltip wording that said "_compared to the 1986-2005 baseline period_".  For some reason, I thought you were talking about the legend wording for the historical maps themselves.

Correct me if I'm wrong, but all of our "Historical occurrence" layers are, in fact, averages from the Idaho dataset for 1986 to 2005 (that's what the file names indicate, anyway).  Assuming that's true, I changed the Time Period for the historical maps to say "1986 to 2005".

IMO, we definitely need new tooltips for the Time Period in the legends to explain exactly what's being shown.  The one we have now for the historical maps is good at explaining the purpose of the historical data, but it doesn't really say what it's based on, and I can imagine users may confuse it for the baseline.

Also, I will update the seedling deployment tool legends to the new style.  Once that's done, I'll close this issue unless you have any objections.

**Comment by hadinon** [comment]
Yes, that is correct about the "Historical occurrence" layers. :)

And actually, I think that the tooltip that's up there now for historical time periods was originally meant for the model baseline tooltip. However, now that I'm reading it, it could probably work for both! At any rate, I think it's fine to leave it "as is" for now since all the tooltips are likely to change soon with Aim 6's suggestions.

Yep, sounds good to me with regards to closing this issue after your other updates!

**Comment by daviswx** [comment]
The legends for the seedling deployment tools have also been updated.  Closing this issue.

Agreed about getting Aim6's thoughts on the tooltip wording.  Let's add that to the list.
