### ISSUE TITLE
Tool-specific landing pages

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#40]
- Change landing page images to not look exactly like the map on the tool itself
- After clicking “Proceed to the Tool”, open it in a new tab
  - Or have the “more info about this tool” link open the landing page in a new tab
- For now, remove the description of thick dark blue error bars on historical range
- Show zoomed-in version of some images, including the timeseries and note features in the text and image as (a), (b), (c) 
- Add 1, 2, 3, etc. to top tab labels so that folks know to step through them?
- Summer Temperature tool description of why it’s important: “Summer temperature is directly linked to the carrying capacity of the land for pine production.  As summer temperatures increase, so does the demand for soil moisture (which may be declining for your area of interest).  Land managers might need to rethink initial stand stocking levels and thinning schedules to promote fewer, but healthier trees per acre.”
- Summer Precipitation tool description of why it’s important: “Summer precipitation is directly linked to the carrying capacity of the land for pine production.  As summer precipitation declines significantly, land managers might need to rethink initial stand stocking levels and thinning schedules to promote fewer, but healthier stems per acre.”

(HIGH PRIORITY)

**Comment by daviswx** [comment]
These changes have been made and all the images have been updated for the climate risk tool landing pages.  I still need to update a few images on the seedling deployment tool landing pages.

For the map screenshots that looked too much like the tools themselves, I have added a white fading around the edges and a "soft glow" on top.  I'm not 100% happy with how they look, but I guess these can be placeholders for now until we think of a better idea.  In some ways, I like what we have on the seedling deployment tool landing pages where we show both a screenshot and another relevant image together.  But I'm not sure what other images we might use for the climate tools.

One change I didn't make was adding 1, 2, 3, etc. to the top tabs.  In my opinion, that would just be unneeded extra information, and I think the tabs are already laid out in a natural left-to-right order ending with the "Proceed to Tool" link.

**Comment by hadinon** [comment]
A few comments...

1) Regarding the summer precip description... can we change it from, "As summer precipitation declines significantly..." to "If summer precipitation declines significantly..." because not all areas of the domain are projected to decline significantly. This may be the case in Eric's neck of the woods (I think he suggested this change) but again, not in all areas.
2) Can we change the "Projected Change" description to this: "The Projected Change maps show the change in conditions for the selected future period given the selected emissions scenario."? The future change is calculated compared to a model baseline historical period but this is different than the historical period mentioned right above and I don't want folks to get confused about that.
3) Under seedling markets --> Location-specific ranges, change "seed" to "seedling".
4) Regarding the map screenshots, instead or in addition to the "fading effect", maybe you could put a word cloud with an important piece of information or a question, such as, "How will average summer temperatures change in the future?" or something like that. The goal being to distinguish this as a screenshot of the tool, not the tool itself. Thoughts?
5) I'm fine with not including the 1,2,3, etc change.

**Comment by hadinon** [comment]
On the Seedling Sources landing page, can we make a few tweaks to the description on the "Cold Tolerance Ranges" tab?
- change the second and third paragraphs to: 

"To display this range for any time period, click the "show 5°F range" option in the legend. That will highlight a range of locations with annual minimum temperatures from 1° cooler to 5° warmer.

When viewing a future risk range, note that the temperatures shown on the center map above the location markers () will change to reflect the value for that particular time period, e.g. 20-year stand, instead of the value for current stands. Also, the values on the side maps will be different than the center map's value for that period because the isotherm location is different for all three maps. More specifically, the minimum projected temperature isotherm will be further north than that of the center map and the maximum projected temperature isotherm will be further south than that of the center map." 

Thoughts?

**Comment by hadinon** [comment]
Another idea for the map screenshots (same comment as in #41 ):

What if we did something like this? The banner title could say the tool name (e.g. "Summer Temperature Tool") and then either don't have a subtitle or have the subtitle repeat the summary description, e.g. "View projected changes in average summertime temperatures". Thoughts?
![image](https://cloud.githubusercontent.com/assets/886682/10045542/80b61d1e-61d1-11e5-96b9-3cb2540f33ac.png)
(screenshot from agroclimate.org)

**Comment by daviswx** [comment]
Responding to you comments:
1. (**Tool Background** tab) Yes, that wording has been changed.
2. (**Map Display Options** tab) Yes, that wording has been changed.
3. (**Location-Specific Ranges** tab) Yes, that wording has been changed.
4. (tool screenshots) That's not a bad idea, and it would let us add in a question each tool is designed to answer, which at one point we discussed adding to the page but never got around to.  Here's a quick mockup.  We could also remove the Map Layer Options menu, Map Help tooltip, PINEMAP logo, and scale bar to make it look less like the actual maps.
   ![extreme_min_temp_historical_v2](https://cloud.githubusercontent.com/assets/9257580/10046310/0ffe09b0-61d6-11e5-99ce-32e7a2937f0d.png)
5. (**Cold Tolerance Ranges** tab for Seedling Sources tool) I changed that description, and the only real problem is that the text doesn't fit on the page without needing to scroll.  Any way we could cut about three lines out?  Also, I get the feeling that this aspect of the tool might be tough to understand until a user is actually interacting with it.  That's even more reason to add a tooltip or some sort of explanation in the attached map legends, as discussed in ncsco/pinemap-dss-help#49.

I wanted to run one other thing by you.  Leslie mentioned that Aim6 and/or SREF have some graphic designers on hand that could help us create the landing page images.  Once we have finalized the look of the maps and data, do you think we might want to use their services?  For a professional tool like this, I feel like we need very high quality images like they can hopefully provide.

**Comment by hadinon** [comment]
Here are my responses:

4) (tool screenshots) Agreed about removing the Map Layer Options menu, Map Help tooltip, PINEMAP logo, and scale bar. I like your question for the Extreme Min Temp tool. Here are some question ideas for other tools:
- Summer Temperature: How will summertime temperature change in the future?
- Summer Precipitation: How will summertime precipitation change in the future?

Do we want to do this for the seedling deployment tools, too?

5) (**Cold Tolerance Ranges** tab for Seedling Sources tool) Here is a reduced text version of the description (3rd paragraph only): 
"When viewing a future risk range, note that temperatures shown on the center map above the location markers () will change to the value for that time period, e.g. 20-year stand, instead of the current stand. Also, side map values will be different than the center map because the isotherm locations are different. More specifically, the minimum projected isotherm will be further north than the center map and the maximum projected isotherm will be further south than the center map."
Does it fit without having to scroll?

6) Yes, we should definitely talk to Leslie about connecting us with their graphic designer folks (after we finalized everything).

**Comment by hadinon** [comment]
Regarding 5), try this instead: "When viewing a future risk range, note that temperatures shown on the center map above location markers () will change to that time period's value, e.g. 20-year stand, instead of the current stand. Also, side map values will differ from the center map because the minimum projected isotherm will be further north than the center map and the maximum projected isotherm will be further south."

**Comment by daviswx** [comment]
Images for the climate tool landing pages have been updated.  Seedling deployment landing page images still need to be updated.

For the **Cold Tolerance Ranges** tab wording, here's another suggestion that clears things up a bit more, IMO:
- When viewing a future risk range, note that temperatures shown on the center map above location markers () will change to reflect that time period's projected minimum temperature instead of the current/historical value. Also, side map values will differ from the center map because the minimum projected isotherm will be farther north than the center map and the maximum projected isotherm will be farther south.

**Comment by daviswx** [comment]
Also, good idea about adding questions to the seedling deployment tool landing page images.  If we are planning to do that for every tool, which is probably a good idea, then we should do it here.  And it may help to further clarify the difference between the tools.

Should those new images still include the map of Schmidtling's guidance?  Or just the historical average map?  Or the projected isotherms map?

**Comment by hadinon** [comment]
Your revised wording for the **Cold Tolerance Ranges** sounds good. 

Regarding the seedling deployment tool landing pages, maybe we can use these as questions: 
- In the future, are you looking to move seedlings from your location?
- In the future, are you looking to move seedlings to your location?

We can possibly even drop the "In the future" part. Also, I like Schmidling's map but I'm leaning towards just including an image of the projected isotherms map to be consistent with the "Tool Background" images on the other tool specific landing pages. Thoughts?

**Comment by daviswx** [comment]
I just saw your suggested questions.  I was already working on versions with different questions, so I went ahead and added those to the landing pages.  They can be changed if desired.

I have also updated the images on the **Location-Specific Ranges** and **Cold Tolerance Ranges** tabs.

Unless any other image or wording edits are needed, the tool-specific landing page updates should be complete.

**Comment by hadinon** [comment]
On the **Location-Specific Ranges** tab for Seedling Sources, is there room at the end of the 1st paragraph to say something like this? "In other words, the temperature of the future source region is expected to match the current temperature at your location during the lifetime of your stand, e.g. 30-years." Does that clarify things a bit more?

**Comment by daviswx** [comment]
Is that explanation backwards?  My interpretation is that the isotherms/source regions show where temperatures are currently as warm as it's likely to be at your location during different future periods.

Maybe I'm thinking about or reading something incorrectly, though.

**Comment by hadinon** [comment]
OK I think my wording there was confusing. How about this? "As an example, over a 30-year stand's lifetime, the current temperature of that future isotherm will migrate to the selected location so a landowner may want to consider pulling seedlings from that future zone."

**Comment by daviswx** [comment]
Hmm that still seems pretty wordy and confusing to me.  Here's an idea for re-writing this tab:

After selecting a location, potential seedling source ranges will be displayed on the map in the form of color-coded bands.  Each band represents a region where current temperatures match the likely future temperatures for a particular time period at your selected location.

As an example, if you're looking to establish a 30-year stand, you may want to recruit seedlings from the region shown in light blue.  Those seedlings should be well-adapted to the wintertime cold temperatures you may see at your location during the lifetime of the stand.

Many of these ranges will overlap, so it may be helpful to toggle some of them off. You can do this by clicking the checkbox next to the period's name in the legend.

This tool is ideal for landowners since it highlights the best source regions for future planting based on likely climate changes.

**Comment by hadinon** [comment]
Yes, that looks good. Two minor suggested changes in bold:
"After selecting a location, potential seedling source ranges will be displayed on the map in the form of color-coded bands. Each band represents a region **with** current temperatures **that** match the likely future temperatures for a particular time period at your selected location."

Otherwise, I think we can close this issue. Do you want me to contact Leslie about the graphic designer connection now or after beta testing?

**Comment by daviswx** [comment]
OK that is now updated.  I will close this issue.

For now, let's hold off on contacting Leslie in case we make any changes to the map displays after beta testing.
