### ISSUE TITLE
DSS overview landing page

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#41]
- Hide the topics in the Environment menu so it doesn’t appear that we’re already viewing something in that menu
- Change DSS description to “What is the DSS?: This Decision Support System, or DSS, is a planning tool for localized climate decisions about loblolly pine establishment, management, and productivity.”
- Pending executive committee approval of the new DSS name, tweak “DSS overview” section to say, “Pine Management Climate Considerations DSS Overview” followed by, “The Pine Management Climate Considerations DSS is a planning tool for landowners and land managers that considers and incorporates localized climate considerations into loblolly pine management decisions. The advanced tools presented in this DSS provides landowners and land managers with a unique ability to implement management practices to improve and/or maintain southern pine forest health, productivity, resistance and resilience to climatic, weather, and other environmental pressures.
  This site aims to assist foresters, professional land managers, and landowners across the southern region of the US, from Virginia through Texas.
  Below is a Quick Start Guide to the primary features and tools.  Click on any of the tabs below to find out more about each tool. Or, to choose a specific tool, click on the View All Tools tab for a complete list of available tools.”
- **Structure** tab wording: “The menus listed at the top of the window correspond to the major stand considerations:  environment, stand establishment…”
- Change image on overall **Structure** tab (it shows the Establishment menu, not the Environment one)
- **Climate Data** tab: “Our tools are based upon a suite of complex climate models.  These models use atmospheric equations and greenhouse gas emissions to not only simulate the current global climate but also project likely future global climate and related impacts.  No one model…”
- On the **Map Layout** tab, replace “or something similar” with “in this example”
  - Another suggestion:
    - Results from each tool is displayed on three maps.
    - The center map, usually titled Mean projected change, displays the average change of the     selected climate variable (example: minimum temperature) for the selected period (example: from 2020 - 2039) and future emissions (example:  current emissions (high) ).  Mean change is calculated as the averaged change over 20 different model simulations.
    - Example: the center map to the right shows the project change in the number of days per year with minimum temperatures below 32°F from 2020 - 2039. The white area indicates little to no change, while the darker green areas show those portions of the South in which the number of days below 32°F for the year 2039 is expected to decrease by 10 - 15 days.
    - Each of the maps allow the same navigational tools.  Double-click to zoom, and click and drag to pan.
- On the **Time Series** tab, consider shortening to “For many tools, when you select a location, a time series is displayed below the map that summarizes future projections for your location.  The time series shows historical observations and variability.  If future projections fall within the historical range, future conditions are likely to be similar to those you have experienced in the past.”
- On the **Time Series** tab, add an example paragraph: “The time series to the right shows the projected change in the average number of days each year that will be 32°F or colder.  Change in days is on the vertical access.  Time periods are listed on the horizontal axis.  Note that the number of days are expected to decrease (fewer days reaching 32°F or below) for the selected location.”

(HIGH PRIORITY)

**Comment by daviswx** [comment]
The first six suggestions have been implemented on the main DSS landing page.

I have some questions about the other suggestions and this landing page in general:
- On the **Structure** tab, I added a new image that's more zoomed in with the non-menu area faded out.  On this image, should we point out the menus, topics, and tools, or is this obvious based on the examples in the text?
- The **Climate Data** tab currently features a direct screenshot from one of the maps, and the alpha testers advised changing or altering these types of images so they don't look as much like the maps themselves.  Are there any better images we could use to describe the MACA data, and if not, would it suffice to just remove the zoom buttons and scale bar from the current image?  I could also try to add some sort of post-processing effects, like blurring the edges or something.
- Their suggestions for the **Map Layout** tab are very specific to the climate risk tools and particularly the Projected Change display.  Since this is the main DSS landing page, I imagine we will want the information to be more broadly applicable to most/all tools (e.g., the seedling deployment tools don't have a Projected Change display).  I think it's fine to use an example from one of the climate risk tools, but the wording may need to be changed so it's not so specific (e.g., "The center map, usually titled Mean projected change...").
- Also, their suggestions for the **Map Layout** tab wording do not include anything about the side maps.  In my opinion, this tab is the first good place to note that (a) the side maps are showing ±2 standard deviations, since we have removed this from the map subtitles, and (b) that you can click the side map titles to enlarge them.  Of course, that info. is repeated in the Map Help tooltip.
- We have a **Time Series** tab on both the main DSS landing page and the tool-specific landing pages.  On the tool-specific ones, we're planning to label specific features of the timeseries, like the columns representing the historical average and future scenarios.  Given that, what should we cover about the timeseries plots on the main DSS landing page?  I could imagine emphasizing the point about "if future projections fall within the historical range, future conditions are likely to be similar to those you have experienced in the past", and superimposing or highlighting that historical range across one or two of the future periods and pointing out which projections fall within or outside of it.  Of course, we don't have the historical ranges calculated yet, which would make this tough to do at this point.

**Comment by hadinon** [comment]
Here are my responses...

1) With regards to the menus, topics, and tools, they seems intuitive to me so I'm good with the way it is currently. What were your ideas for pointing out the menus, topics, and tools?
2) For the **Climate Data** tab.... yes, maybe try blurring the edges a bit? Or, we could highlight the zoom buttons and/or Map Help icon by labeling them on the image, which would make it obvious that it is not the tool itself or maybe that's more appropriate for the **Map Layout** tab? Another option would be to add a label to the map that says some basics about the MACA data, e.g. downscaled output from 20 climate models, ~6km spatial resolution, etc. Thoughts?
3) Yes, I agree about not having this super specific to any particular type of tool.
4) Agreed. I think repetition is good :)
5) Hmmm yes good point. Could we use this space as an opportunity to talk about how these do not show model error but instead, the range of likely future outcomes?

**Comment by hadinon** [comment]
For the **Climate Data** tab, what if we did something like this? The banner could say "Climate Data" and then the subtitle say, "DSS tools use a state of the art downscaled climate dataset called Multivariate Adaptive Constructed Analogs (MACA)". Thoughts?
![image](https://cloud.githubusercontent.com/assets/886682/10045542/80b61d1e-61d1-11e5-96b9-3cb2540f33ac.png)
(screenshot from agroclimate.org)

**Comment by daviswx** [comment]
1. (**Structure** tab) Here's a sample version with annotations added for the menus, topics, and tools.
   ![menu_structure_hl](https://cloud.githubusercontent.com/assets/9257580/10044968/c6b19136-61cc-11e5-9b37-5b103625bcff.png)
2. (**Climate Data** tab) I thought of a couple different ideas.
   Version A:
   ![maca_data_v2a](https://cloud.githubusercontent.com/assets/9257580/10045649/74bc3592-61d2-11e5-894d-ddf4d1bdd379.png)
   Version B:
   ![maca_data_v2b](https://cloud.githubusercontent.com/assets/9257580/10045651/77309e58-61d2-11e5-9d45-b925a1586c45.png)
   My concern with using the "Climate Maps" example you mentioned is that we're not using a banner and subtitle on any other landing page images.
3. (**Map Layout** tab) I will work on the wording so it's not specific to any one tool.  I will also update the image for this tab.
4. (**Time Series** tab) Yes this might be a good place to discuss what the "error bars" actually represent.

**Comment by hadinon** [comment]
1) Ahh I see what you mean now by pointing out the menus, topics, and tools. I like your example. Another idea is to label the image with (a), (b), (c) similar to what you did for the time series tab on the climate-related tool-specific landing pages.
2) Version A is my favorite. I agree with your concern about the "Climate Maps" example.
3) and 4) Sounds good.

**Comment by daviswx** [comment]
More suggestions based on our discussion:
- (**"What is the DSS?** paragraph) Delete the sentence beginning "The advanced tools..." since this info. is repeated in the next bullet and on the DSS Tool Matrix page.
- (**Climate Data** tab) Include an introductory paragraph (1-2 sentences) about MACA.  Idea: "DSS tools use the University of Idaho's Multivariate Adaptive Constructed Analogs (MACA) dataset, which was created using 20 global climate models and two different emission scenarios at a spatial resolution of 6 km."
- (**Map Layout** tab) Change tab title to "Three-Map Layout".  Revise the first sentence to say that it applies to model projections.  In the next two paragraphs, remove the clauses with bolded map titles.  Update the image to remove the map legend and add an arrow across the bottom with labels saying "Minimum likely outcome" and "Maximum likely outcome".
- (**Time Series** tab) Add a note clarifying the error bars (see Heather's comment above).  Zoom in on the time series (maybe of the Summer Precip. tool?) for the image.
- Somewhere on the page (maybe on the **Structure** tab?), add a note about the recommended browsers and screen size.

**Comment by daviswx** [comment]
All of these changes have now been implemented, and the wording and images on the DSS Overview landing page have been updated.  Please advise whether any other changes are needed.  Otherwise I think we can close this issue.

**Comment by hadinon** [comment]
At first, I hit CTRL-F5 and the images did not update on the **Climate Data**, **Three-Map Layout**, and **Time Series** tabs. However, after I cleared my browsing data, everything looks to be updated so I'll go ahead and close this!
