### ISSUE TITLE
Keep marker on map if data is N/A?

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#47]
I'm not sure if this would go into an existing issue so I decided to create a new issue... :+1: 

Is it possible to keep the marker on the map if a user clicks a location that doesn't have data? It looks like it initially "drops a marker" on the map after the click (see below) but then removes it when the message appears stating there is no data at that location. I believe this would apply to all current tools. My thinking is that someone might switch to a different map display (playing off the ~9 sec attention span idea) and then forget where they clicked. Thoughts?

Drops the marker right after the click:
![image](https://cloud.githubusercontent.com/assets/886682/9933889/240b8900-5d1c-11e5-8ed1-8db4b515f0dc.png)

Marker disappears once the "no data" message loads:
![image](https://cloud.githubusercontent.com/assets/886682/9934502/d878c8e6-5d1f-11e5-98b9-f0a402e181d2.png)

**Comment by daviswx** [comment]
When I implemented the function to clear the selected location when the [X] is clicked, I decided to call that function when an invalid location was selected also.  That's why the markers completely disappear in this case.  But I agree that it's probably unnecessary to call it there.

I have commented out that function call so it should no longer remove the markers when a location with no data is selected.  Let me know if you notice any problems with it, or any cases when it would be needed (I can't think of any, though).
