### ISSUE TITLE
Map Zoom

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#62]
*Don’t let users zoom too close.  Always show at least 4 grid cells on the map.
*Experiment with OL3 zoom duration feature: http://openlayers.org/en/v3.9.0/apidoc/ol.control.Zoom.html
(LOW PRIORITY)

**Comment by daviswx** [comment]
I have adjusted the maps so you can't zoom in closer than the county level (when the map is about 4x8 grid cells).

I also experimented with the zoom duration feature, but it turns out that it only applies to the +/- zoom buttons, not scroll wheel zooming.  So I don't know whether anything can be done about that.

I did figure out how to disable the scroll wheel zooming, though:
http://artarmstrong.com/blog/2014/10/28/openlayers-3-disable-mouse-wheel-on-zoom/

**Comment by daviswx** [comment]
Task: disable scroll wheel zooming before the DSS rollout

**Comment by hadinon** [comment]
Task: add zoom controls to side maps

**Comment by daviswx** [comment]
Also, be sure to update the FAQ box(es) to note the new scroll and zoom behavior.

**Comment by daviswx** [comment]
Done.  Scroll wheel zooming is disabled (but double-click zooming is still allowed, as noted in #68).  Zoom controls now show on all 3 maps.  And the FAQ box above the map reflects the new behavior.
