### ISSUE TITLE
Discrepancy between map and time series values

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#67]
On the Summer Precipitation tool, the Projected Change map mean value does not match up with the value on the time series for that same time period and emissions scenario. Are you able to replicate?

![image](https://cloud.githubusercontent.com/assets/886682/11477181/ca06421a-9754-11e5-8ab8-33d0caab1108.png)

**Comment by daviswx** [comment]
Should be fixed now.  This bug was introduced when I switched to the faded bar plots.  These bars don't contain mean information, so it was just duplicating the minimum value for the mean.  As a fix, I am just averaging the min and max values to get the mean.

Also, I noticed this error on all 3 climate risk tools, so it should be fixed on all of them.
