### ISSUE TITLE
Change our map extent?

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#7]
Note: this bug applies to all current tools (seedling deployment, summer precip, extreme min temp). I am using Firefox 38.0.1.  Here's the bug: when I regridded the historical avg file, something really weird happened in northern MN. I know this isn't in our PINEMAP domain but I'm wondering if OpenLayers has the ability to not display that anomaly in the data which extends northward into Canada? 

Also, related... on the seedling deployment tools, it is doing something really weird when I click outside the US but not in the ocean (say, Canada)... gives a value of -18457.9F! The same appears to happen on the climate risk tools, too, (except it says 0 days) but I haven't tested that as thoroughly. 

Please let me know if you need additional clarification or are unable to replicate. Thanks!

**Comment by daviswx** [comment]
I can only think of one problem with restricting the domain: Currently at the widest zoom level, you can fit most of CONUS within the map display, so we would have to remove this zoom level since it shows as bit of that anomaly.  After some searching, I also couldn't find any way to mask out part of a layer in OpenLayers or with THREDDS WMS calls.

I know it would require re-generating a few of the historical average files, but could those be re-run to ignore any points above a certain latitude or y value?  I think you'll still have to do another historical run anyway to get the range, so maybe the average file could be re-generated then as well?

Also, good catch with the extreme values over non-US landmasses.  I have a place in my code that catches clicks over the ocean, but not over land where we don't have data.  For a while now, I've been meaning to modify this to be a bit more robust and actually see whether there's data for a clicked point before returning the click results and timeseries.  I'll move this up my to-do list.

**Comment by hadinon** [comment]
Thanks, Corey. I "cropped" the historical avg file for summer precip, extreme min temp, and seedling deployment tools. The filename will be the same except there is "_dss" at the end. They are located in the same directories. Once you update the filenames, let me know and I can test out the tools.  If that looks good, we can probably mark this as closed since it sounds the "extreme values over non-US land" issue is on your to-do list. :+1:

**Comment by daviswx** [comment]
OK the historical maps are updated for all 4 tools (2x seed deployment, extreme min temp, summer precip).  If they look good to you, feel free to close this issue out.  I will create another issue about the no-data values.

**Comment by hadinon** [comment]
Looks good. Thanks!
