### ISSUE TITLE
Add the summer dryness tool

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#70]
Data is ready so add this tool to the DSS.

What should the tool be called?

We need two descriptions for this tool:
- a short tool description for the menu
- a slightly longer tool description and application for the topmost FAQ box

We also need color ramps.

What units does summer dryness index use?

**Comment by daviswx** [comment]
@hadinon will check notes from Evan for explanations

**Comment by daviswx** [comment]
The Summer Dryness Index tool is now in place on the development DSS site.

Custom color ramps have been created for the average and change maps.

We still need tool descriptions for the menu matrix and the topmost FAQ box.  @hadinon has emailed Harold Burkhart (VT) about applications of this data.

The maps may need to be clipped to remove some of the crazy values from Texas westward, which may be outside of the geographic range for which this index was intended.  We're also awaiting guidance from Harold about that.

**Comment by hadinon** [comment]
Here are a few updates on this:
- Harold's description of summer dryness index for the DSS:  "The dryness index is growing degree days divided by annual precipitation (Table 2 in Sabatia and Burkhart 2014 Forest Ecology and Management). This variable was found useful in predicting loblolly pine site index from biophysical variables. Summer droughts affect stand productivity. The impact of a summer drought depends on the soil type and the stage of development of the stand. Future projections of summer dryness should provide useful guidance for selecting genetic material to plant and prescribing silvicultural treatments at the time of loblolly pine plantation establishment, as well as informing stand management decisions over the rotation."
- Harold recommended limiting inference to the present range of loblolly pine because empirical data for modeling is limited to that geographic extent. Therefore, Ryan will build a shapefile mask, which will be overlaid on the summer dryness maps 
- Need to ask Harold whether there a standard color ramp. Heather will first check his paper. 
- Once we have mask and color ramps in place, send sample of output to Harold

**Comment by hadinon** [comment]
Also, should we link to the paper Harold mentioned above in the "Other Resources" section? http://www.sciencedirect.com/science/article/pii/S0378112714002588
Note: the paper did not contain color maps so I will email Harold about a recommended color ramp

**Comment by hadinon** [comment]
Update from conversation with Harold and discussion at our PINEMAP meeting today:
- there is no standard color ramp used for summer dryness index so let's plan to use existing color ramps (historical observed / projected average one and projected change one) on the summer dryness tool.
- Ryan is working on the shapefile mask

**Comment by daviswx** [comment]
The shapefile mask is in place.  Here are some other things we do/may need to update on this tool:
- The tool description in the main menu and in the topmost FAQ box
- A tooltip for the map and time series titles, possibly explaining how Summer Dryness Index is calculated.  (Note from issue #83: mention why the data is not being displayed for western US)
- Possibly divide the values by 10 (did we for sure decide to do this?)
- Possibly tweak the color ramp bounds.  Only in the most extreme case (2080-2099, RCP 8.5, Highest Likely Outcome) do the maximum values on the color ramp get used.  Likewise on the Projected Change maps, the ramps could probably be stretched over a smaller range of values (say, -150 to +150) so the changes are a bit more evident, especially in the shorter-term periods.

**Comment by daviswx** [comment]
Updates from today's meeting:
- Descriptions for the main menu and FAQ box are still needed _(this needs to be ready if we want to do a commit tomorrow morning)_
- A tooltip for the map/time series title is still needed _(this won't be included in tomorrow's commit since it isn't ready for the other tools)_
- Yes, show the values divided by 10
- Yes, tweak the color ramps to show values from 0 to 30 and change values from -15 to +15

**Comment by daviswx** [comment]
The new color ramps and values are in place.  I ended up making the Average maps go from 0 to 36 and the Change maps from -16 to +16 because those ranges split up evenly among the number of colors I had specified.

I think the new values definitely show some more of the variations, especially in the Historical map and the short-term ranges.

**Comment by hadinon** [comment]
The new color ramps look good!

One thing I just remembered is that I haven't calculated historical variability maps yet. This would be quite the undertaking since this variable has lots of calculation steps and thus, it wouldn't be ready today. Are we OK to push this tool to production without the historical side maps?

When you mention description for the main menu, do you mean the text that currently says, "View projected changes in average Summer Dryness Index"? If so, I'm good with what that says but am open to other suggestions.

Here's my attempt at a FAQ box description: "Summer dryness index is useful in predicting loblolly pine site index from biophysical variables. Summer droughts affect stand productivity. The impact of a summer drought depends on the soil type and the stage of development of the stand. (insert line break  here?) Future projections of summer dryness should provide useful guidance for selecting genetic material to plant and prescribing silvicultural treatments at the time of loblolly pine plantation establishment, as well as informing stand management decisions over the rotation."

Lastly, can you add a link to Harold's paper within the "Other Resources" section of this tool? http://www.sciencedirect.com/science/article/pii/S0378112714002588

**Comment by daviswx** [comment]
OK I have added that FAQ box description and a link to the paper.

No problem that the other historical maps aren't ready.  It's fine to push to production with only the Historical Average map.

Should we change the description in the main menu?  Currently, it says "View projected changes in average Summer Dryness Index", which may not mean much to people if they don't know what Summer Dryness Index is.  I'm thinking we could change "average Summer Dryness Index" to a short summary that may be more meaningful.

**Comment by hadinon** [comment]
Hmmm good point about the main menu description. Maybe we could say, "View projected changes in the ratio of summer growing degree days (5C base) to summer precipitation."?

Also, the Sabatia and Burkhart paper appears to be linking to the USDA Plant Hardiness Zone map. I even cleared my cache!

**Comment by daviswx** [comment]
Oops, that would be because I copied the Plant Hardiness Zone resource link but forgot to change the URL!  It's fixed now.

The new title is also in place.  I just dropped the 5C base part so it would fit on two lines.

**Comment by hadinon** [comment]
Sounds good. The only remaining action items here (although not required before pushing to production) are: 
- send screenshot of DSS output to Harold 
- create historical variability maps

**Comment by hadinon** [comment]
OK whoops I didn't mean to unassign you! I thought two people could be assigned a task. Well, I'll switch it back to you and just mention that the final action items are assigned to me. :smile:

**Comment by hadinon** [comment]
So, there's been lots of extension workshops this week and I'm hearing that people are confused! As suggested by Tim, can we add this to the summer dryness index tool's "What can this tool be used for?" FAQ box? 
"Summer dryness index is calculated as growing degree days divided by precipitation.  If temps stay the same and precip goes down, the index will go up.  If precip stays the same and temps go up, the index will go up.  In any particular location a change in the index should be a useful measure of relative drought stress."

Maybe something like this....
"Summer Dryness Index -- calculated as growing degree days divided by precipitation -- is useful in predicting loblolly pine site index from biophysical variables. If temperatures stay the same and precipitation goes down, the index will go up. If precipitation stays the same and temperatures go up, the index will go up. 

In any particular location, a change in the index should be a useful measure of relative drought stress and summer droughts affect stand productivity. The impact of a summer drought depends on the soil type and the stage of development of the stand.

Future projections of summer dryness should provide useful guidance for selecting genetic material to plant and prescribing silvicultural treatments at the time of loblolly pine plantation establishment, as well as informing stand management decisions over the rotation."

**Comment by hadinon** [comment]
P.S. it is kind of long and I'm in favor of short but if folks are reading these and are still confused then we may need to rethink which is what I was trying to do here. I hope that makes sense!

**Comment by daviswx** [comment]
It's definitely a bit lengthy, but I'm fine with it if it helps clarify things better.  Maybe there are some ways we can trim it just a bit.  I'll try to think about that later.

I am slightly confused by the first sentence of the second paragraph.  Particularly, the part "... a useful measure of relative drought stress and summer droughts affect stand productivity" doesn't really make sense to me; it seems like two separate thoughts that are strung together.

**Comment by daviswx** [comment]
Task: Look into why the Summer Dryness Tool is returning 0 values for points outside the clipped area.

**Comment by daviswx** [comment]
Once the projected data layers are also clipped to the PINEMAP region, this issue with 0 values _should_ go away (or at least be easier to diagnose).

Also, any thoughts about the wording above regarding the text for the FAQ box?  Just wanted to get clarification on that before adding it in.

**Comment by daviswx** [comment]
After digging a bit deeper in my code, I have made an update that fixes this.  Previously, if a value was less than 0 (like -9999.0), I was setting it to 0.  I have commented out that section so these invalid/missing values will be treated as such.

I suppose we still need to clip the future maps to the PINEMAP region, but for the moment, clicking points outside this region on the historical map will show the "Historical data is unavailable" message rather than a 0.0 value.

**Comment by hadinon** [comment]
Awesome, thanks for the update. I will let you know when the clipped projection files have been generated. 

As far as the FAQ box, we can break the 1st sentence of the 2nd paragraph into two such that it reads, "In any particular location, a change in the index should be a useful measure of relative drought stress. Summer droughts affect stand productivity." -- would that help?

Also, a quick comment on the title tooltip: it should say, "...summertime precipitation..." instead of "annual precipitation". 

I guess the "create historical variability maps" is no longer an action item here!

Other than that, I sent a screenshot of the clipped DSS output to Harold. Once the clipped projection files are created, I plan to ask him what he thinks about clipping those western Gulf loblolly "islands" where IMO the relationship falls apart, especially in the later future time periods.

**Comment by daviswx** [comment]
OK, I see what you were saying in the second paragraph.  Here's what I changed it to:

"Summer droughts affect stand productivity, so at any particular location, a change in the Summer Dryness Index should be a useful measure of relative drought stress."

The tooltip has also been updated, although that may be removed or replaced at some point given our discussion in #83.

**Comment by daviswx** [comment]
We still need to clip the projected maps to the native loblolly region.

Also, I will check on a possible bug with time series plots not showing up when on the Projected Change display.

**Comment by daviswx** [comment]
The issue with the time series not showing up for the Projected Change display should be fixed.  For this tool, I had set that any values less than 0 were invalid, but of course, the change maps can have negative values.  I have now changed that threshold for invalid data to -100.

**Comment by hadinon** [comment]
The clipped summer dryness index files have now been generated for the historical map as well as for all future maps. 

A few notes: 
1) R's raster package complained about one of the summer dryness attributes, grid_mapping: crs, which is in the original daily MACA files and got trickled through to the MACA DSS files. When I removed it with NCO, the script worked properly. This does not appear to affect how the files are rendered in Godiva. Note for future reference (related to this): the MACA files are unprojected with a datum of WGS84 (EPSG: 4326).
2) The crop() function in R complained that the extents of the MACA DSS raster and native loblolly shapefile do not overlap. This is because the longitudes in the original MACA files are non-negative, e.g. 235 instead of -125 (360 degrees difference). This convention also got trickled through to the MACA DSS files. In contrast, the longitudes in the loblolly shapefile are negative values. So, I subtracted 360 degrees to get negative longitudes within the MACA DSS files. This does not appear to affect how the files are rendered in Godiva.
3) When the new netCDF is written out as the originalfilename_clipped.nc file, the time dimension and time variable are removed so any OPeNDAP calls within the DSS will need to account for this, e.g., remove the [0:1:0] part. This does not appear to affect how the files are rendered in Godiva.
4) When the new netCDF is written out as the originalfilename_clipped.nc file, the 0,0 point is defined as the top left corner instead of the bottom left corner. The originalfilename.nc MACA DSS files define 0,0 as bottom left corner. In order to get them to match, I ran a quick conversion to switch the clipped files back to being defined as the bottom left corner. Action item: once the new clipped files are in the DSS tool, I'll run some tests to make sure Godiva output matches up with the tool output, which will verify that this is all working properly.

Good news: the script is fully dynamic now so 15 arguments fed to the script will produce the clipped output. This will come in handy if we ever need to clip the output for future DSS tools.

**Comment by daviswx** [comment]
The new maps are now in place on the DSS, and after adjusting my scripts to account for not including the time dimension when needed, the time series should be working as well.

Everything seems fine from the spot checks I've done, but let me know if you notice any problems with the data on the maps or time series.

By the way, now that we've clipped the maps, I'm noticing that it's a bit tough to see what's happening on the Change maps, especially in the shorter-term periods where most values in the eastern half of the region are white.

If you think this is a problem, maybe we could adjust this color ramp so the zero value is a non-white color.  We probably wouldn't want to use gray since that's what we were planning for the error maps, but perhaps something else could work.

**Comment by daviswx** [comment]
The Change map color ramp has been tweaked so points with data are easier to distinguish between masked-out points.  The numerical extent of values has also been reduced for all map displays.

I will close this issue with the next commit to the public site.

**Comment by hadinon** [comment]
Everything looks good and I finally was able to test the DSS output with Godiva output. They match up!

One very minor suggestion: Can you update the title tooltip (map and time series) to say, "This parameter was developed within the native range of loblolly pine trees so values are unavailable outside of this region." instead of, "This parameter was developed for the Southeast US so values are unavailable west of this region."? Not even worth reopening the issue IMO :wink:

**Comment by daviswx** [comment]
This has been fixed and updated on the dev site and public site.
