### ISSUE TITLE
How to handle min/max projected change map placement

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#8]
We discussed this the other day but I wanted to log it here so I didn't forget! Here is a note from Corey about the extreme min temp tool: "the leftmost one [map] is actually showing 2 std devs above the mean change instead of below it.  However, since the mean change is negative, looking two standard deviations below a negative number gives an even more negative number, which would imply a greater change than the mean.  So to make the interpretation correct of a minimum change being smaller than the mean change, I reversed the left and right maps". 

Overall, we may want a better wording here. We could ask Ryan and/or beta testers for feedback.

**Comment by daviswx** [comment]
Here's our preliminary solution for this problem:
- Reverse the Max/Min Projected Occurrence maps so lower values are on the left
  - Should the "2 standard deviations above/below the mean" labels also be switched?
- Change the map labeling to read "X fewer days" instead of "-X days" (see issue ncsco/pinemap-dss-help/issues/23)

**Comment by daviswx** [comment]
I have implemented the "inverted" map fix for the Extreme Min Temperature tool.

The Projected Change maps are the same as before.  The **_least negative values**_ will appear for the **Minimum Projected Change** and the **_most negative values**_ will appear for the **Maximum Projected Change**.

The Projected Average maps are now inverted.  The **_smallest values**_ will appear for the **Minimum Projected Change** and the **_greatest values**_ will appear for the **Maximum Projected Change**.

**Comment by hadinon** [comment]
Everything looks good to me! On the Projected Change maps, can we switch the "2 standard deviations above/below the mean" labels (as you mentioned above)? Do you think a tooltip is worthwhile for the left and right Projected Change maps? I envision this would only apply to the extreme min temp tool. It could say something as simple as what you've explained before, such as: "In most cases, the left map shows two standard deviations below the mean. In this case, the mean change is negative. So, looking two standard deviations below a negative number gives an even more negative number, which would imply a greater change than the mean. Therefore, in this case, the right map shows two standard deviations below the mean. For the same reasoning, the left map displays two standard deviations above the mean." Thoughts?

**Comment by daviswx** [comment]
I have a few thoughts and questions about this that may determine how we proceed:
- With the way we are now presenting the change information -- as "X fewer days" instead of "-X days" -- we have basically removed the negative component of the data.  That may complicate things if we try to explain the reason for the difference as being due to a negative number.  Granted, we still do show negative numbers in the map legend and timeseries Y-axis labels.
- I'm no statistical expert, but I have been trying to decide whether the subtitles are technically correct as they are.  If we consider the change as an absolute value (which is sort of what we're doing it by calling it "fewer days"), then two standard deviations below the mean would be subtracting an absolute value standard deviation, which gives a smaller number.  And that's what the left map shows now.
- Does knowing this distinction about being above or below the mean really even matter for the end user?  Sure, it's of statistical interest, but I wonder if switching the subtitles from the way they are on every other tool  and adding a tooltip would just add unneeded information and potential confusion.

I'm certainly open to ideas about this, but my own inclination is to keep things simple like they are now, and I _think_ the way we're presenting it is correct, even if we're using sort of a roundabout way to calculate it on the back end (subtracting from negative numbers, etc.).

**Comment by hadinon** [comment]
Based on the discussion that we just had, I'm adding this to the list of questions for beta testers. In the meantime, do we want to go ahead and remove the subtitles saying two standard deviations above/below the mean on the left and right maps?

**Comment by daviswx** [comment]
Yep I have hidden it for now.  Do we want to add some sort of tooltip for these?  Or include an explanation on the landing page(s)?  Or ask the beta testers about that?

**Comment by hadinon** [comment]
I vote for asking the beta testers for guidance on this. I envision these questions:
- Is it useful to know how these side maps are calculated? OR would it be helpful to know that the side maps represent two standard deviations above/below the mean?
- Do you think our audience will care about this?
- If yes, where should we include this explanation? subtitle, map tooltip, timeseries tooltip, landing page(s), other

Thoughts?

**Comment by daviswx** [comment]
Just to re-state what we just talked about, we could assess whether the beta testers understand what the side maps are showing and give multiple choices.  One of the answer choice options should be something like "the model error".

**Comment by hadinon** [comment]
Here are some other options for the multiple choice question about what beta testers think the side maps are showing:
- Values from the model(s) with the highest/lowest values 
- One standard deviation above/below multi-model mean
- Two standard deviations above/below multi-model mean
- 1st and 99th percentiles
- 5th and 95th percentiles
- First and third quartiles 
- Model error
- Other

Do you have any edits / suggestions?

**Comment by daviswx** [comment]
A couple other ideas I thought of:
- The bounds of historical variability overlaid on the model projections
- The expected changes at the beginning, middle, and end of the selected period

**Comment by daviswx** [comment]
Updates on this issue based on beta tester feedback:
- A majority of testers (6 to 3) prefer using comparative terms for the change map labels instead of a plus or minus.
- A majority (5 out of 8) also knew that the side maps were showing ±2 standard deviations.  Those five testers all said they knew that because it was clearly stated in the DSS.  Two testers thought it showed the highest and lowest values from any model, and one thought it was the historical variability overlaid on the model projections.
- There was an overwhelming consensus (8 out of 9) that DSS users should have a rough idea of what the side maps are showing.
- Testers were split on where such an explanation should go: 3 said it should go on the DSS Overview landing page (where it already is), 3 said it should go on individual tool landing pages, 5 said it should go in a subtitle just below the map title, and 6 said it should go in a tooltip on or near each map.  Note: Only 2 people thought it should go in both a subtitle _and_ a tooltip.

I'm guessing we don't want to add explanations in all of these places, so maybe we stick with it on the DSS Overview landing page (but bold it or something) and add a tooltip or subtitle?

It could also be part of a general overview of the map that would appear when the user first visits any DSS tool, although we haven't yet decided whether to add this (it's on our list of follow-up questions for the small group discussions).

**Comment by hadinon** [comment]
When summarizing small group feedback, we combined this issue with another one so see #31 for action items. Because of that, I'm going to go ahead and close this issue. 

A few notes... by using subtitles with percentiles, it becomes more appropriate (IMO) to always call the left side map "2.5th percentile" and right side map "97.5th percentile" even with negative changes because we say "X days fewer" so it is an absolute value and each tail represents 2.5%.
