### ISSUE TITLE
Suggestions for seedling deployment tools

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#80]
The idea for new tool names came from Mark Megalos so I'm pasting parts of his email about this:

I love this tool but I wonder if it has been mislabeled the while time.  It's really a hardiness zone map of a different color. Might we call it what it truly is....
- Safe planting zones
- reasonable deployment tool
- Pine Hardiness Zones (It's catchy and people are already predisposed to think in those terms)

Related to each tool description... 
One lets you plan how far from the south you can take material from safely ( and improve productivity) now and in the future.
The other is for future planning... how far north you may move current material (genetics, family, provenance, clone) assuming you are around to do it

**Comment by daviswx** [comment]
Do you know which of the three names applied to each tool?  I'm assuming Safe Planting Zones would be for the Seedling Markets tool, but I could also imagine Reasonable Deployment could apply.  And to me, Pine Hardiness Zones applies to the historical maps on both tools but not necessarily for the future maps.

**Comment by hadinon** [comment]
I'm not 100% sure. Let's see if we can catch him today and ask for more details. We may want to ask him or Steve McK about Tomasz' comments regarding these tools.

**Comment by hadinon** [comment]
Action item here: 
- set up a call with Mark, Gary, and Tomasz to discuss names. Possible discussion points:
  -- probably needs to be called something related to cold risk since it doesn't include genetics
  -- ideas for tool names: southerly sources & northern cold, push & pull 
  -- idea for category name: pine hardiness
- under "Other Resources", point to Tree Improvement Coop's PRS system and/or their cold risk maps

**Comment by daviswx** [comment]
Based on our conversation with Gary and Mark today, we decided to rename the "Seedling Deployment" category to something like "Dynamic Hardiness Zones".

I also suggested new names for each tool:

Seedling Markets :arrow_right: Cold-Tolerant Markets for Nurseries
Seedling Sources :arrow_right: Source Ranges for Greater Productivity

(Note: I tweaked that second wording so the title would fit on one line in the menu)

I will get these updated in the development DSS soon, along with updating all references to "Seedling Markets" and "Seedling Sources" in the tooltips and FAQ boxes.

Mark also suggested that we could tweak the topmost FAQ box to phrase the question in a more meaningful way, like "How can I increase the productivity of my stand?".

If you made any more detailed notes of the suggestions in our meeting, feel free to add them here.

**Comment by hadinon** [comment]
Yep, that matches with my notes!

As far as the topmost FAQ box, I also wrote down this question: "How far north can I push the genetics of my current seed source that I'm comfortable with?" but it sounded like none of us loved that exact wording so there's probably room for improvement there. As for the other question you mentioned, Mark initially suggested a longer wording, "How can I get better productivity by looking at a southern seed source?" but I'm guessing you shortened it to get it to fit on one line. :) Maybe we could list the longer question as the first statement when you open the FAQ box and/or turn it into a sentence instead of a question? For example, the first one could be, "This tool can help you determine how far north you can comfortably push the genetics of your current seed source." 

Related, someone at our meeting with Karen and Lindsay suggested adding a statement at the beginning of these FAQ boxes that said, "Minimum temperatures are increasing so this tool shows locations where you might want to plant in the future." Thoughts?

**Comment by daviswx** [comment]
I have updated the section title ("Dynamic Hardiness Zones") and tool titles in the menu and on the tools themselves.

I also tweaked the tool descriptions in the menu.  Here's what I have now:

> **Cold-Tolerant Markets for Nurseries**
> View northerly regions where seedlings could be deployed in the future without an appreciable change in cold risk
> 
> **Source Ranges for Greater Productivity**
> View southerly regions where seedlings could be recruited from to increase productivity; ideal for landowners

And I updated the wording in the topmost FAQ boxes for each tool:

Markets tool:

> **FAQ:** How can this tool help identify new seedling markets?
> 
> This tool shows the projected future locations of annual extreme minimum temperature ranges, which roughly correspond to USDA Plant Hardiness zones.
> 
> As minimum temperatures increase in the future, seedling markets will migrate northward, so seedlings from a given location can be planted farther north without much added cold risk.
> 
> This tool builds on guidelines from Ron Schmidtling (a Research Geneticist with the US Department of Agriculture) that suggest seedlings can be moved to locations with extreme minimum temperatures up to 5°F cooler without appreciably increasing the risk of cold damage.

Sources tool:

> **FAQ:** How can this tool help increase productivity?
> 
> This tool shows the current locations of future minimum temperature ranges, which roughly correspond to USDA Plant Hardiness zones.
> 
> Seedlings from these zones with warmer temperatures are generally more productive, so by pulling seedlings from these ranges, you can get the benefits of this productivity without much added cold risk.
> 
> This tool builds on guidelines from Ron Schmidtling (a Research Geneticist with the US Department of Agriculture) that suggest seedlings can be moved from locations with extreme minimum temperatures up to 5°F warmer without appreciably increasing the risk of cold damage.

**Comment by daviswx** [comment]
Also, after seeing the eye tracking results that suggest some people had trouble using these tools, I was just thinking about how we could make them more intuitive.

In my mind, the intended steps in using this tool are:
1. Select a location to view the general pattern of extreme minimum temperature migration
2. Identify a specific period to investigate further, and isolate it (i.e., turn off all other ranges)
3. View details about that period, like the 5° range or model error

I think we addressed any issues getting to step 1 by adding the note about selecting a location below the Projected Temperatures map display option.  Of course, there may still be an issue with people not knowing to click the map, but we can address that with other changes.

I'm not sure how many people realize that you can check/uncheck the ranges to view specific ones.  From the eye tracking data we viewed, at least one person did this.  But I realize that the tools don't include any specific instructions to suggest that this is possible.

And from the eye tracking results, only 19 out of 31 people (61%) ever found the "show 5° range" option, so that's clearly a step that isn't clear for many users.

To address steps 2 and 3, I mocked up a possible new legend layout that's not so squeezed together and includes some instructions to (hopefully) guide users through these steps.

Here's what it might look like when a location has first been selected and all ranges are being shown:

![seedlingmarkets-newlegend_showall](https://cloud.githubusercontent.com/assets/9257580/13534388/dbb9ce20-e202-11e5-8ccc-903ae822b036.png)

And here's what it might look like when a specific location is selected:

![seedlingmarkets-newlegend_period](https://cloud.githubusercontent.com/assets/9257580/13534406/f07b1d50-e202-11e5-824f-bbdb2f419897.png)

Once the model error output is ready, we could add it to the dropdown menu.

Note that since this design uses radio buttons instead of checkboxes, only a single range can be displayed at a time, so we could effectively skip the step of having users manually select the "show 5° range" link.  In other words, once they select a time period, it would automatically show that range instead of just showing the thin isotherm.

**Comment by daviswx** [comment]
I've got the new legend layout in place for the markets tool.  It's not yet functional yet, but it gives a good idea of what it will look like:

![image](https://cloud.githubusercontent.com/assets/9257580/13673361/b07f0e3e-e6a6-11e5-8ceb-5f01b2dc3efa.png)

**Comment by daviswx** [comment]
The updated legend display and functionality is now in place on both seedling deployment tools.

As I mentioned yesterday, this re-structuring gave me a chance to clean up and simplify some of the back-end code.  I think everything is working correctly, but it's always possible that I missed updating something and there's an errant function call that no longer works.  So let me know if you notice anything like that.

Also, I'm not sure what the best wording is for the legend section titles ("All Periods", "Recent Conditions", "Short-Term Planting", "Long-Term Planting").  I worry that Short-Term and Long-Term Planting may be interpreted as planting _for_ the short-term or long-term instead of planting _in_ those periods.  So any suggestions are welcome.  Note that the titles can be different for each tool.

**Comment by daviswx** [comment]
I have changed the legend section titles to say Short-Term/Long-Term Deployment and Recruitment instead of Planting.  There may still be better options for these, so let me know if you have ideas.

**Comment by hadinon** [comment]
Bug report: for "Recent Conditions: Historical", show center map only since it is the same as the side maps. Change center map title to "Historical average".

![image](https://cloud.githubusercontent.com/assets/886682/13926483/ecc7fd14-ef62-11e5-8081-b9812dbbc815.png)

**Comment by hadinon** [comment]
Ideas: 
- remove the word "projection" such that the year range XXXX-XXXX fits on same line as color
- change "Recent conditions" to "Historical" and just have 1986-2005 with black color on same line
- put all 4 on the same line horizontally (stacking short-term and long-term periods vertically) in this order: historical, short-term, long-term, all periods

**Comment by daviswx** [comment]
I have updated the legend on the Markets tool to reflect the changes we discussed.  To save vertical space, I put all of the individual period options on the same line, with the "Show all periods" option on the next line.  I'm not sure if this is the best place for it, so let me know if you have any suggestions.

Also, I changed the section heading to "Planting Period" since I thought that was a simpler way to describe what's being shown, and how users should interpret it.

![image](https://cloud.githubusercontent.com/assets/9257580/13932172/44b8d290-ef7d-11e5-917a-52d912befc0f.png)

**Comment by daviswx** [comment]
This new legend got the stamp of approval, so I will copy it over to the Sources tool.

**Comment by daviswx** [comment]
The new legend is now in place for the Sources tool.

**Comment by hadinon** [comment]
Looks good! I sent an email to Steve McK asking if [this](http://www.state.sc.us/forest/prs-c1.pdf) was the best fact sheet to highlight in order to accomplish this action item:
- under "Other Resources", point to Tree Improvement Coop's PRS system and/or their cold risk maps

**Comment by hadinon** [comment]
Potential minor tweak: should we change the statement at the bottom of the page from, "For more information on seedling deployment, contact..." to "For more information on dynamic hardiness zones, contact..."?

**Comment by daviswx** [comment]
This wording change has been made.  Once we hear back from Steve McKeand, we can add a fact sheet and/or other links to the Other Resources section.

**Comment by hadinon** [comment]
In playing around with the new tool options menus (which look awesome BTW!), I noticed something that may be potentially confusing to users but I'm not 100% sure how to get around it. After selecting your location from the map, the "Projected Temperatures" map pops up with the historical average planting period shown by default. However, the confusing part is the fact that the radio button says "Projected Temperatures" and there is an option to show a Future Emissions scenario yet we are showing by default the 1986-2005 current temperature range. The current part is reflected in the title of the tool but my concern is that it will be confusing due to "current" not being included in the other areas that I mentioned. However, I'm stuck because I think we want to show them the current planting period by default so that they can compare future ones to the current. OK, here's my suggestion (note: this is pretty outside the box so bear with me):

What if we displayed the 1986-2005 range on the "Historical Observed" map display instead of on the "Projected Temperatures" display? The only potential limitation here is that when users come to the tool, it would be a blank map until they click or enter lat/lon. I think that's OK as long as we make it clear that they need to select their location. The other thing is that IMO there is a value in seeing the historical range overlaid with all other time periods on the "Projected Temperatures" display. I think we can keep this as part of the "Show all time periods" option by saying "Show all time periods including the historical period 1986-2005 (in black)" or something to that effect. We certainly have the horizontal real estate to put a longer blurb there. Thoughts?!

Also, since this thread has sort of morphed from the original post about changing the names, I've changed it to a more general title: "Suggestions for seedling deployment tools".

**Comment by daviswx** [comment]
Idea: Change the displays to **Historical Hardiness Zones** and **Location-Specific Ranges**.

**Comment by daviswx** [comment]
And hide the Future Emissions box when the Historical range is selected.

**Comment by daviswx** [comment]
These new display names are now in place, and the functionality of having the Future Emissions options hidden when the historical range is chosen should also be working.

**Comment by daviswx** [comment]
Also, hide the Future Emissions part of the map legend when the historical range is displayed.

**Comment by daviswx** [comment]
That is now fixed.

**Comment by hadinon** [comment]
Ross had an appealing statement within his write-up for the Tree Improvement Coop that might be useful for the dynamic hardiness zone "About this tool" FAQ box or possibly as a title tooltip? Here's what I'm thinking:

Cold-Tolerant Markets for Nurseries:
"This tool shows the projected future locations of annual extreme minimum temperature ranges, which roughly correspond to USDA Plant Hardiness zones. These future changes in hardiness zones have the potential to create new markets for cold-tolerant seedlings."

Source Ranges for Greater Productivity:
"This tool shows the projected future locations of annual extreme minimum temperature ranges, which roughly correspond to USDA Plant Hardiness zones. These future changes in hardiness zones may change seed source ranges of planting stock for greater productivity."

Let me know what you think. Again, probably too minor to warrant opening the issue back up.

**Comment by daviswx** [comment]
I like both of these ideas.  I'm thinking that this could become the text for the "About This Tool" boxes, and we can link to more info. on the new DSS FAQ page including parts of the current, longer descriptions.

**Comment by hadinon** [comment]
Yes, I like it. Speaking of DSS FAQ page, I'm going to take a look at that issue next!
