### ISSUE TITLE
Tooltips, FAQs, and other DSS explanations

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#83]
Comment from Tomasz Koralewski about the Extreme Min Temp tool:

It may be a bit confusing whether the number of days is a total number of days in a calendar year, in a season, and perhaps whether or not this is a continuous period.

**Comment by hadinon** [comment]
I'm not sure how to clarify this further than what we have in the FAQ or title. I may ask Tomasz if he has any ideas. I wrote the below for Leslie and Martha's training. It is too long for the FAQ but maybe we can link to it?! Thoughts?

As an example, you can determine how the average number of freezing days (or days below 32°F) will likely change in the future at your location of interest. These future values are calculated using daily minimum temperature data simulated by a climate model. The days with minimum temperatures below 32°F are counted up for each year. Then, these numbers are averaged across a particular set of years. For example, one of the future time periods contains the years from 2060 to 2079.

**Comment by daviswx** [comment]
IMO, the map and time series titles make this very clear: it's the average number of days per year.  Not sure how we could be much more clear than that.

The map labels and time series tooltips only say "days", but again, I think the titles should make it obvious exactly what it's showing.

**Comment by hadinon** [comment]
Yes, I agree. Maybe he's curious about the methodology. We talked about having a section for detailed methodology descriptions under "Other Resources"? Could we have them click a link called "Detailed Methodology" within "Other Resources" and then it pops up a paragraph like the one I provided above? Otherwise, the document would only be a paragraph long so I'm not sure if that's useful. Thoughts?

**Comment by daviswx** [comment]
I agree that it probably wouldn't be used/useful, and I'm not sure if a description of the methodology would answer his question anyway.  His question about whether it's in a continuous period is really confusing to me -- how else would you count the number of days?!  Maybe he has some broader uncertainties or is somehow missing the titles/labels in the DSS.

**Comment by hadinon** [comment]
Add a tooltip on the title that says, "The days with minimum temperatures below 32°F are counted up for each year. Then, these numbers are averaged across a particular set of years."

Do similar for summer precip and temperature. I will add verbiage soon.

**Comment by hadinon** [comment]
Note for summer dryness index title tooltip: mention why the data is not being displayed for western US

**Comment by hadinon** [comment]
Ideas for the summer dryness index title tooltip: "The summer dryness index is growing degree days divided by annual precipitation (Table 2 in Sabatia and Burkhart 2014 Forest Ecology and Management)."
Mention limiting inference to the present range of loblolly pine because empirical data for modeling is limited to that geographic extent.

**Comment by daviswx** [comment]
I have added tooltips to the map titles for the Summer Dryness and Extreme Min Temp tools.  When tooltips are written for the other tools, I can add those as well.

Should these tooltips also be included in the time series title?  Or is one occurrence per tool sufficient?

**Comment by daviswx** [comment]
Survey says yes, duplicate this tooltip in the time series title.

**Comment by daviswx** [comment]
The tooltips will now show next to the time series titles as well.

**Comment by hadinon** [comment]
Title tooltip verbiage for the remaining tools:
- Summer Temperature: "To generate this output, average temperature is computed for each year during the summertime months of June, July, and August. Then, these annual values are averaged across a 20-year period." 
- Summer Precipitation: "To generate this output, precipitation is summed for each year during the summertime months of June, July, and August. Then, these annual totals are averaged across a 20-year period."
- Seedling Markets and Sources -- Historical Map: "To generate this output, the day of year with the lowest minimum temperature is determined for each year. Then, these annual values are averaged across a 20-year period. In other words, it shows what the temperature has historically (on average) been on the coldest day of the year, similar to what is shown on the USDA Plant Hardiness Zone Map."

Note: these all (including the Extreme Min Temp and Summer Dryness Index ones) describe how the historical average maps are calculated not necessarily how the projected change and projected average are computed. Can we add a statement at the end of all that says something like, "_Projected Change_ data indicate the amount and direction (positive or negative) that this quantity is expected to change in the future. _Projected Average_ data show future values of this quantity by adding the change values to the historical values." AND change the "To generate this output..." part of the above to, "To generate this output using a _historical_ dataset, ..."  Thoughts?

**Comment by hadinon** [comment]
I just spoke with Bill Hubbard and he had a good explanation for Seedling Markets. I'm not sure if it's useful here but I thought I'd mention it. "Current guidance from Schmidtling's research suggests planting seeds in locations that are up to 5 degrees cooler than your location. However, minimum temperatures are expected to increase in the future. Therefore, this 5 degree zone is going to move in the future. This tool shows this future 5 degree zone where you might want to consider planting in the future." Maybe we could tweak the FAQ box description??

**Comment by daviswx** [comment]
It's not a problem to tweak the wording for each map display, but keep in mind that the Historical Observed and Projected Average time series show both historical and projected data, so the tooltip for those displays should be pretty much the same (if not identical) so it applies to both.

I'm a bit torn on these tooltips because in my opinion, simpler -- and shorter -- is better, but I can also see the benefit of having the explanation about the Projected Change or Projected Average datasets.

With that said, here's an example wording for the Summer Temperature that I think balances both:

**Historical Observed and Projected Average displays/time series:**
To generate this output, the average temperature is computed for each year during the summertime months of June, July, and August. Then, these annual values are averaged across a 20-year period.

While the Historical Observed display shows the range of past outcomes -- from the average to less-frequent extremes -- the Projected Average display shows the likely spread in only the average value, so year-to-year variations should still be expected.

**Projected Change display/time series:**
To generate this output, the average temperature is computed for each year during the summertime months of June, July, and August. Then, these annual values are averaged across a 20-year period.

Projected Change data indicate the likely shift of the average annual value in the future.

**Comment by hadinon** [comment]
Yes, I definitely like making the distinction between the 3-map historical and 3-map projected average. The Historical Observed explanation is good but can we change the Projected Average to this? "...the Projected Average display shows the likely spread of future outcomes across 20 models for a 20-year period."

I guess my major concern with the first paragraph is that's just simply not 100% how the Projected Change and Projected Average are calculated. Well, it is sort of correct for Projected Change. The two statements are true but the future 20-year period is then used to find a multi-model mean different/change by calculating 20-year Future Projection minus 1950-2005 Climate Model Baseline -- and this difference is done for every model then the differences are averaged across 20-models to obtain the multi-model mean difference/change, which equals the Projected Change center map. (I'm not even getting into the mean +/- 2 std deviation calculations needed for the side maps.) The Projected Change is added to the Historical Observed to obtain the Historical Average map. So, how do we capture all that accurately in one sentence?! So, yeah, that's why I suggested what I said before. Gosh, this is all so complex!

**Comment by daviswx** [comment]
OK, I think I understand what you're saying.  So you're concerned that we're oversimplifying the process of creating the Projected Average data?  Like we're basically saying that we're just averaging the annual values, when in fact, we're adding the average mean (or +2 stddev, or -2 stddev) Projected Change data for each 20-year period to the Historical Average.

There's probably some way we could re-word it to capture that detail, although it would make clarifying the difference between Historical and Projected a bit tougher since they are calculated quite differently.

When I wrote those descriptions, I think I was most concerned with emphasizing that the Projected Average data is showing the likely shift in the _average_, not the full range of expected variability like the Historical Observed data captures.  That's yet another complexity that's probably worth noting!

With that in mind, I'm a bit concerned that we can't truly capture these complexities in a single tooltip without them getting really long.  That's especially true if we have to describe the Historical Observed and Projected Average calculatons in the _same_ tooltip.

Since this process is the same for every tool, should it be outlined and linked elsewhere?  We have a description of how the future changes and averages are generated on the DSS FAQ site, but it's buried halfway down the page so it might not be very visible there.

IIRC, the original idea behind the title tooltips was to explain the basics of the calculations for each tool; e.g., the Extreme Min Temp tool is an average annual count of days below a certain threshold.  Trying to add extra information about the historical and/or projected calculations seems like it might be too much for one tooltip.

**Comment by daviswx** [comment]
One other potential concern about having title tooltips: They contribute to tooltip overload at the top of the page, and with so much overlap, it renders them all tough to read or place the context for.

![image](https://cloud.githubusercontent.com/assets/9257580/13357583/0b1739f8-dc79-11e5-93c1-a8c78ddaaf48.png)

I remember that we also discussed having a short description beneath each title instead of a tooltip.  Maybe those descriptions could go in an expandable box beneath each title?  We would have a bit more room there for explanations, so we could potentially include those more detailed explanations of the historical or projected calculations.

If we did that, I think it would be easiest to not have the same expandable explanation for the time series.  Having to include both historical and projected explanations is really cumbersome, and if the explanations are provided further up the page, I don't see as much value in duplicating it.

**Comment by daviswx** [comment]
In our discussion with Ryan, we talked about keeping any descriptions -- whether they're in tooltips or below the title -- brief, but link to other information that can explain things better.

That linked information could be in the form of a fact sheet including information about how the tools were generated (e.g., the historical vs. projected data), any intricacies with the data (e.g., why the Summer Dryness tool only has data for the PINEMAP region), and examples of applications with the data.

**Comment by hadinon** [comment]
Is it possible to add a link to a tooltip? If not, maybe our path forward is to have an expandable explanation box beneath each map title and add a link there?

**Comment by daviswx** [comment]
We could add a link in a tooltip, but I'm still a bit wary about having too many tooltips, especially since we now know that hardly anyone actually looks at them.

And now that I think about it more, I'm not so keen on having a separate expandable text area either.  My rationale is that (a) people don't seem to read text on the page or tooltips anyway, and (b) it might be good to reduce the complexity of different explanations as much as possible by not scattering them between tooltips, FAQ boxes, expandable text areas, and even the DSS Introduction and MACA FAQ pages.

For first-time page users, I can imagine all of these explanation types are confusing and a bit overwhelming, and the more we add, the easier it gets to lose track of them or ignore them entirely.  Of course, I also understand the need to have these explanations and make them accessible.

Just thinking out loud here, but what if we could reduce the sources of explanations to only 2 or 3:
- Keep the DSS Introduction page but re-structure the text and images as described in #93.  On or at the bottom of each tab, we could possibly link to more information about certain topics on a separate page (described below), like the historical and projected data.
- Revamp the MACA FAQ page into a more general DSS FAQ page.  Along with the content that's already there, we could add specific explanations of how the historical and projected data is generated; basically, what we were going to put in the title tooltips or the expandable explanations.  This information pretty much covers what's in the current tooltips, so we could remove those entirely since people don't look at them much and/or replace them with the third option.
- Keep the FAQ boxes or something like them for each tool, but to reduce the amount of text in each box to a short explanation with a link to the relevant part of the DSS FAQ page.  This is sort of what we were thinking for the expandable explanation areas.

Of course, we'll continue to have the Other Resources section for external links, papers/factsheets/other PDFs, contact info., and potentially citation information.  But at least in my mind, it might be simpler, more convenient, and more usable to have a centralized location for all of our explanations.

Feel free to tell me if you think this is a bad or unworkable idea, or any problems you can see with it.  Also, since you dealt more directly than I did with Leslie, Martha, and others for their workshops, can you think of any specific points of confusion or training needs they had?  I'm thinking that we could structure the DSS FAQ page as a general guide for learning how to use the DSS and what sort of information is in it.

**Comment by daviswx** [comment]
Here's an example of the new tooltip design I've been working on.  It's sort of a hybrid combining the look of the current tooltips, the explanations of the FAQ boxes (albeit more brief), and links to information on the new/expanded DSS FAQ page I have described.

Here's what the tooltip would look like when un-expanded:
![image](https://cloud.githubusercontent.com/assets/9257580/13852169/58841e9a-ec37-11e5-8e14-d4b89716201e.png)

And here's what it would show when hovering over it:
![image](https://cloud.githubusercontent.com/assets/9257580/13852216/797ea4b2-ec37-11e5-8933-1e5dabf7d15f.png)

Obviously there might still be a concern about whether people will actually look at these, but I do think there are a few advantages to them:
- The tooltips display on hover, _not_ on click
- These tooltips would be shorter but with links to more information, which means less initial reading for users
- By going to just one uniform explanation/tooltip style on the page, these may be easier to find and their purpose may be more obvious
- They're not as gaudy or invasive as the current FAQ boxes

If you like the idea for the expanded FAQ page, I will create a shared Google Doc so we can start brainstorming ideas for questions and answers that should go on that page.

**Comment by daviswx** [comment]
I had another idea for how the tooltips could be incorporated.  Along with having the icon available, we could use a text underline, like in the legend here:
![image](https://cloud.githubusercontent.com/assets/9257580/13858536/7dbf9a90-ec55-11e5-9d5d-24b56b9c48f2.png)

When hovered over, it would give the same effect:
![image](https://cloud.githubusercontent.com/assets/9257580/13858541/82427254-ec55-11e5-8fc6-23405a895e60.png)

**Comment by daviswx** [comment]
The new tooltip style is now in place on the page.  There are four different versions: a small question mark, a large question mark (not currently used anywhere), a large question mark with a title, and highlighted text.

Once the new DSS FAQ page is ready, we can optionally add links at the bottom of the tooltips to more info. on that page.

**Comment by daviswx** [comment]
I have updated the wording for some FAQs and added a few others that you wrote in the _DSS FAQ page content_ document.  A few other FAQs still need review or revision (especially the "Tools in the DSS" ones), and we probably want to re-order them as well.  But for now, they're at a state of relative completion.

I also finished building in the ability to link to a specific FAQ page item and have it display.  With that in place, it will be easy to link to items from each other, from the Intro page, and from tooltips on the tools themselves.  As time allows, I will work on adding that while we're at the meeting next week, so maybe we could potentially highlight it during our presentation time on Thursday morning.

Also, once the tool-specific FAQ items are written, we may want to go back through the tooltips for each tool and shorten them, since some are fairly long at the moment.

**Comment by daviswx** [comment]
I have begun linking tooltips with questions on the FAQ page.  Some tooltips need to be edited and condensed a bit, and the FAQ page contents probably need to be reviewed or edited as well.  Any important terms in the FAQ answers could also be bolded.

Also, I'm thinking that not all tooltips necessarily need to be linked with the FAQ page.  For example, the "Map Help" tooltip provides a concise explanation of the map functionality as it is, so I'm not sure that we need to link it to the FAQ page unless we expand that explanation about using the maps.

**Comment by daviswx** [comment]
**FAQ update:** We have revised and rewritten most of the FAQs and updated them on the PINEMAP DSS and Climate Voyager dev sites.  Only a few tool-specific FAQs (Dynamic Hardiness Zones and Plant Hardiness Zones) still need to be written.

**Question:** On the FAQ page, should we only show one answer at a time?  Right now, you could potentially open every answer on a tab, which could be cluttered and confusing.  The only downside I could think to showing one at a time is that if you click one of the embedded links in an answer, it would close that answer and open the other one.  Granted, this could essentially happen anyway if you click to view an answer that happens to be on a different tab.

**Tooltip update:** I have been going through the existing tooltips and adding links to FAQs wherever it's appropriate.  Several tooltips are also pretty long -- especially the climate model baseline one and the time series one -- so I'm going to pare those down a bit.

**Question:** Several months back, we decided to add tooltips in the map titles for some tools, e.g., the Minimum Temperature Thresholds and Summer Dryness Index tools have ones explaining the calculation steps and why the SDI isn't available outside of the native loblolly range.  Now that we have written tool-specific FAQs that largely include this information, do we still need these tooltips in the map titles?  I would vote to get rid of them since it would remove some redundancy, clean up the page a bit, and get rid of one more thing that we'd have to maintain or update if we make changes.

**Comment by hadinon** [comment]
**Answer 1:** Is there a way to have a max limit on the number of tabs that are open at a time, say 3? If not, perhaps just have it show one at a time.

**Answer 2:** Yes, I agree about removing these map title tooltips. Folks interested in more details about how the tool is calculated, for example, can click the link to "Additional tool details" under the "About This Tool" tooltip. So, I think we're covered! 

**Bug:** The "About model error" link within the "model limitations" / "what is the model error?" tooltip seems to be broken but maybe I need to clear my cache :wink:

**Comment by daviswx** [comment]
**1:** To my knowledge, there is no way to limit the number of tabs open at one time.  You can either open something in the same tab or in a new tab, but browsers really don't give much control beyond that.  I'm also in favor of showing only one at a time, so I have updated the FAQ page to have that functionality.

**2:** Okay, I have removed those tooltips from the Minimum Temperature Thresholds and Summer Dryness Index tools.

**Bug:** That link should now be fixed.  On a related note, please see issue #91 for some possible wording options for the model error/limitations tooltip.

**Comment by hadinon** [comment]
All sounds and looks good. Are there any outstanding action items related to this issue? The only thing that I can think of is revisiting the tool-specific FAQs for the other tools, e.g., Dynamic Hardiness Zones.

**Comment by daviswx** [comment]
Yes, we still need to write FAQs for the Dynamic Hardiness Zones and Plant Hardiness Zones tools.  Besides that, the other FAQs and tooltips have been updated.
