### ISSUE TITLE
Suggestions for Seedling Deployment Tools

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#84]
Comments from Tomasz Koralewski about Seedling Deployment tools:
- Option “Projected Temperatures” is disabled in both “Seedling Markets” and “Seedling Sources” until the map is clicked – then the view automatically changes to “Projected Temperatures”
- Schmidtling actually suggested that better growth can be expected when seedlings are moved somewhat north, with the optimum yield in areas with minimum temperatures about 5°F cooler than the provenance.  In areas cooler than that growth gradually decreases and risk of mortality increases.
  
    --The suggestion to recruit trees from zone where predicted ΔT will be 0-5°F cooler during 2080-2099 (80-year stand) may be not a good option.  Before the temperature warms up as projected, planted young trees would need to endure much colder (current) temperatures in that area before e.g. mid-century, which may increase mortality in young age.
  
    --“Seedling Markets” maps, “show 5° range” feature – the logic should be reversed: the temperature range for a place with T = T0 should range from Tmin = T0 – 5°F to Tmax = T0 + 1°F (unlike “Seedling Sources”).  It is because we are looking to move seedlings to cooler areas, i.e., north – currently the map shows from where to take a seed for a given location, e.g.:

![image](https://cloud.githubusercontent.com/assets/886682/12920837/51ac01be-cf18-11e5-921b-681090b6dbc6.png)

**Comment by hadinon** [comment]
- I will explain to him why we gray out the "Projected Temperatures" option but we may want to add a note somewhere about why this is the case.
- I _think_ we did this properly but maybe we explained it backwards in the FAQ?! I need to ponder it more and wrap my head around it.

**Comment by daviswx** [comment]
Ah, I think I understand what he's saying, and he might be correct.  Since we're highlighting the range around the _future_ (not the current) deployment zone/isotherm, you could theoretically move seedlings even farther north than the isotherm indicates.  Otherwise, if you're moving it to more southerly locales, you're not getting the full benefit of the northward movement.

For the Seedling Sources tool, our approach of showing the range highlighting warmer temperatures should be correct, since you'd want to source your seeds from as warm/southerly of a location as possible to get the full benefit.

I also need to think over this a bit more, but maybe we should also ask Gary about it to make sure we're all on the same page.

**Comment by daviswx** [comment]
Possibly add some text to the menu noting that Projected Temperatures can only be displayed when a location is selected.

Proceed with updating the 5° ranges for the Seedling Markets tool.  This will require adding a new color palette to THREDDS, but the other changes required for this should be straightforward.

**Comment by hadinon** [comment]
Bug report: After location is selected and you switch back to historical map display, it currently keeps displaying the "Future Emissions" options. We discussed not showing those options unless "Projected Temperatures" is being displayed.

**Comment by daviswx** [comment]
A note has been added in the main menu stating "_(select a location to view projected temperatures)_".  This note disappears once a valid location is selected.

The bug with the Future Emissions option has been fixed.  It now goes away when the Historical Temperatures are being viewed.

I will work on updating the color palettes for the 5° ranges so those will show the northward ranges.

**Comment by daviswx** [comment]
Quick update on this: The new, reversed color ramps for the Seedling Markets tool aren't in place just yet.  I had them ready last week but John said they broke THREDDS, so we will do some troubleshooting to get them working.

**Comment by daviswx** [comment]
The reversed color ramps are now working for the Seedling Markets tool.  FYI, the reason the palettes initially broke THREDDS is apparently because there is a character limit for palette file names.  I had previously named them something like this:

`pinemap_seed_deploy_range_high_base_reverse.pal` (47 characters)

I changed them to be something like this:

`pinemap_seed_deploy_reverse_high_base.pal` (41 characters)

So apparently something between 41 and 47 characters is the limit.

I think that's all for this issue, unless we still need to contact Gary about anything.  But after talking to Ryan last week, I think we were all in agreement that showing the ranges this way was correct.

**Comment by hadinon** [comment]
Sounds good, thanks for the update. The only other thing we might want to tweak is the FAQ for each tool. Should the "warmer" mentioned in the 2nd paragraph be changed to "cooler"?

**Comment by daviswx** [comment]
I tweaked the wording for the FAQ boxes to match what each tool shows.

**Seedling Markets:** "...seedlings can be moved to locations with annual minimum temperatures up to 5°F cooler without appreciably increasing the risk of cold damage."

**Seedling Sources:** "...seedlings can be moved from locations with annual minimum temperatures up to 5°F warmer without appreciably increasing the risk of cold damage."

**Comment by daviswx** [comment]
Suggestions from Ryan for the Seedling Sources tool:
- Change the title to "Seedling Source Ranges for a 20-Year Stand at Your Selected Location"
- Change source range titles in the legend to "Source range for planting in YYYY-YYYY"

**Comment by daviswx** [comment]
I have updated the title and source range names on the Seedling Sources tool as suggested by Ryan.

**Comment by hadinon** [comment]
As we discussed earlier, we may want to take a look more closely at the descriptions on these tools, e.g. 5 degree range explanations below the maps.

**Comment by daviswx** [comment]
Task: Change the wording in the 5° range legends on the sources tool.  Ryan suggested this: "Current range for projected cold tolerance in the XXXX-YYYY period"  The markets tool legend is fine.

**Comment by daviswx** [comment]
A slightly tweaked version of this new wording is now in place: "Current range of cold tolerance for the projected XXXX-YYYY period"

I am closing this issue, but the other suggested changes for the seedling deployment tools are still documented in #80.
